const LEGACY_SHEET='Assignment Saves';
const MODERN={'founding-documents-assignment-i':{sheet:'Assignment I',count:28,possible:28},'founding-documents-phase-iii':{sheet:'Phase III',count:10,possible:20}};

function setup(){const ss=SpreadsheetApp.getActiveSpreadsheet();ensureLegacy_(ss);ensureDrafts_(ss);Object.keys(MODERN).forEach(k=>ensureModern_(ss,MODERN[k]));ss.toast('American Studies Worksheet Hub backend is ready.');}
function doPost(e){try{let d={},action='';if(e.parameter&&e.parameter.payload){action=String(e.parameter.action||'submit');d=JSON.parse(e.parameter.payload||'{}');}else{d=JSON.parse((e.postData&&e.postData.contents)||'{}');action=String(d.action||'save');}if(d.assignmentKey)return saveLegacy_(d);validateModern_(d);if(action==='save')saveModernDraft_(d);else if(action==='submit')submitModern_(d);else throw new Error('Unknown action.');return json_({ok:true});}catch(err){return json_({ok:false,message:String(err.message||err)});}}
function doGet(e){const p=e.parameter||{};let r;try{if(p.action==='load')r=loadLegacy_(p.assignmentKey,p.email);else if(p.action==='retrieve')r=loadModernDraft_(p.assignmentId,p.email);else throw new Error('Unknown action.');}catch(err){r={ok:false,found:false,message:String(err.message||err)};}return jsonp_(p.callback,r);}

function saveLegacy_(d){if(d.action!=='save')throw new Error('Unknown action.');const lock=LockService.getScriptLock();lock.waitLock(10000);try{const sh=ensureLegacy_(SpreadsheetApp.getActiveSpreadsheet()),row=findLegacy_(sh,d.assignmentKey,d.email),a=d.accepted||{},total=Object.keys(d.answers||{}).length,score=Object.keys(a).filter(k=>a[k]).length,p=total?Math.round(score/total*100):0,v=[[d.assignmentKey||'',d.assignmentTitle||'',d.name||'',d.period||'',String(d.email||'').toLowerCase(),new Date(),d.status||'in_progress',score,total,p,JSON.stringify(d)]];if(row)sh.getRange(row,1,1,v[0].length).setValues(v);else sh.getRange(sh.getLastRow()+1,1,1,v[0].length).setValues(v);}finally{lock.releaseLock();}return json_({ok:true});}
function loadLegacy_(key,email){const sh=ensureLegacy_(SpreadsheetApp.getActiveSpreadsheet()),row=findLegacy_(sh,key,email);if(!row)return{ok:true,found:false};return{ok:true,found:true,payload:JSON.parse(sh.getRange(row,11).getValue()||'{}')};}
function findLegacy_(sh,key,email){const last=sh.getLastRow();if(last<2)return 0;const vals=sh.getRange(2,1,last-1,5).getValues(),k=String(key||''),m=String(email||'').toLowerCase();for(let i=0;i<vals.length;i++)if(String(vals[i][0])===k&&String(vals[i][4]).toLowerCase()===m)return i+2;return 0;}

function saveModernDraft_(d){const lock=LockService.getScriptLock();lock.waitLock(10000);try{const sh=ensureDrafts_(SpreadsheetApp.getActiveSpreadsheet()),key=d.assignmentId+'|'+d.email,vals=sh.getDataRange().getValues(),record=[key,new Date(),d.assignmentId,d.email,JSON.stringify(d)];let row=0;for(let i=1;i<vals.length;i++)if(vals[i][0]===key){row=i+1;break;}if(row)sh.getRange(row,1,1,record.length).setValues([record]);else sh.appendRow(record);}finally{lock.releaseLock();}}
function loadModernDraft_(id,email){if(!MODERN[id]||!email)return{ok:true,found:false};const key=id+'|'+String(email).toLowerCase(),vals=ensureDrafts_(SpreadsheetApp.getActiveSpreadsheet()).getDataRange().getValues();for(let i=vals.length-1;i>=1;i--)if(vals[i][0]===key)return{ok:true,found:true,payload:JSON.parse(vals[i][4])};return{ok:true,found:false};}
function submitModern_(d){const lock=LockService.getScriptLock();lock.waitLock(10000);try{const spec=MODERN[d.assignmentId],sh=ensureModern_(SpreadsheetApp.getActiveSpreadsheet(),spec),g=gradeModern_(d.assignmentId,d.answers),row=[new Date(),d.studentName,d.period,d.email,d.assignmentId,g.score,g.possible,g.completion];for(let i=0;i<spec.count;i++)row.push(d.answers[i]||'');row.push(g.notes.join(' | '));sh.appendRow(row);deleteModernDraft_(d.assignmentId,d.email);}finally{lock.releaseLock();}}
function deleteModernDraft_(id,email){const sh=ensureDrafts_(SpreadsheetApp.getActiveSpreadsheet()),key=id+'|'+email,vals=sh.getDataRange().getValues();for(let i=vals.length-1;i>=1;i--)if(vals[i][0]===key)sh.deleteRow(i+1);}

function gradeModern_(id,answers){if(id==='founding-documents-phase-iii'){const topics=[['libert','right','relig','jury','due process'],['check','balance','branch','veto','confirm','impeach','court'],['federalist','anti-federalist','tax','revenue'],['slav','territor','civil war','free'],['national','state','federal'],['amend','right','speech','relig','search','trial','due process'],['people','preamble','elect','represent','vote'],['education','school','knowledge','citizen','democra'],['articles','tax','commerce','enforce','constitution'],['document','democra','right','government','evidence']];let score=0,notes=[];answers.forEach((a,i)=>{const t=norm_(a),w=t?t.split(/\s+/).length:0,hit=topics[i].some(k=>t.indexOf(k)>=0);let p=0;if(w>=20)p=1;if(w>=45&&hit)p=2;score+=p;if(p<2)notes.push('Q'+(i+1)+': teacher review');});return{score,possible:20,completion:answers.filter(a=>String(a||'').trim()).length+'/10',notes};}const keys=[['natural','inherent','life','liberty'],['people','permission','governed'],['protect','secure','rights'],['state'],['tax','revenue','commerce','trade','enforce'],['weak','tax','trade','national'],['freedom','liberty','relig','jury','due process'],['school','education','knowledge'],['relig','jury','due process','search'],['slavery','servitude','prohibit','banned'],['represent','elected','republic'],['population','sixty thousand','60000','statehood'],['equal','same status','same rights'],['national','state','shared','divided'],['legislative','executive','judicial','congress','president','court'],['limit','constitution','law','power'],['separate','branch'],['check','balance','veto','override','confirm','impeach'],['supreme','federal','state'],['necessary','proper','carry','execute','implied'],['people','we the people','elect','represent'],['federalist','ratif','strong','national'],['anti-federalist','central','liberty','rights'],['bill of rights','protect','liberty','rights'],['fair','procedure','fifth','5th','due process'],['assemble','gather','first','1st'],['detention','jail','court','prisoner','unlawful'],['limit','government','congress','shall not','right']];let score=0,notes=[];answers.forEach((a,i)=>{const t=norm_(a),w=t?t.split(/\s+/).length:0,hit=keys[i].some(k=>t.indexOf(k)>=0);if(w>=4&&hit)score++;else notes.push('Q'+(i+1)+': teacher review');});return{score,possible:28,completion:answers.filter(a=>String(a||'').trim()).length+'/28',notes};}

function validateModern_(d){if(!MODERN[d.assignmentId])throw new Error('Unknown assignment.');if(!String(d.studentName||'').trim())throw new Error('Student name is required.');if(!String(d.period||'').trim())throw new Error('Period is required.');if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(String(d.email||'')))throw new Error('A valid school email is required.');if(!Array.isArray(d.answers))throw new Error('Answers are missing.');}
function ensureLegacy_(ss){let sh=ss.getSheetByName(LEGACY_SHEET);if(!sh)sh=ss.insertSheet(LEGACY_SHEET);if(sh.getLastRow()===0){sh.appendRow(['Assignment Key','Assignment Title','Student Name','Period','School Email','Last Saved','Status','Score','Total','Percent','Payload JSON']);sh.setFrozenRows(1);style_(sh,11);}return sh;}
function ensureDrafts_(ss){let sh=ss.getSheetByName('Drafts');if(!sh)sh=ss.insertSheet('Drafts');if(sh.getLastRow()===0){sh.appendRow(['Key','Saved','Assignment ID','School Email','Payload']);sh.setFrozenRows(1);style_(sh,5);}return sh;}
function ensureModern_(ss,spec){let sh=ss.getSheetByName(spec.sheet);if(!sh)sh=ss.insertSheet(spec.sheet);if(sh.getLastRow()===0){const h=['Submitted','Student Name','Period','School Email','Assignment ID','Provisional Score','Points Possible','Completion'];for(let i=1;i<=spec.count;i++)h.push('Q'+i);h.push('Teacher Review Flags');sh.appendRow(h);sh.setFrozenRows(1);style_(sh,h.length);}return sh;}
function style_(sh,n){sh.getRange(1,1,1,n).setBackground('#12355b').setFontColor('#ffffff').setFontWeight('bold');}
function norm_(v){return String(v||'').toLowerCase().replace(/[^a-z0-9\s-]/g,' ').replace(/\s+/g,' ').trim();}
function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON);}
function jsonp_(cb,o){cb=String(cb||'callback').replace(/[^\w$]/g,'');return ContentService.createTextOutput(cb+'('+JSON.stringify(o)+');').setMimeType(ContentService.MimeType.JAVASCRIPT);}
