(function(){
const SRC={dep:"https://www.loc.gov/classroom-materials/united-states-history-primary-source-timeline/great-depression-and-world-war-ii-1929-1945/",newdeal:"https://www.archives.gov/milestone-documents/social-security-act",road:"https://history.state.gov/milestones/1937-1945/american-isolationism",war:"https://www.archives.gov/research/african-americans/ww2-pictures",intern:"https://www.archives.gov/education/lessons/japanese-relocation",navajo:"https://www.archives.gov/research/native-americans/military/code-talkers.html"};
const mode=location.pathname.includes("vocabulary")?"vocabulary":location.pathname.includes("review")?"review":"intro";
const meta={intro:["AS-B5-CS19-21-INTRO-2026","Block 5 Intro — Depression, New Deal, and World War II","CS 19–21 • Economic collapse, expanded federal action, the road to war, mobilization, and marginalized groups."],vocabulary:["AS-B5-CS19-21-VOCAB-2026","Block 5 Vocabulary — Depression, New Deal, and World War II","CS 19–21 • Twenty-eight essential terms for economic crisis, war, and the home front."],review:["AS-B5-CS19-21-REVIEW-2026","Block 5 Comprehensive Review — Depression, New Deal, and World War II","CS 19–21 • Thirty-two application, cause-and-effect, comparison, and synthesis questions."]}[mode];window.BLOCK_CONFIG={assignmentKey:meta[0],title:meta[1],description:meta[2],practice:"Connect the causes and effects of the Great Depression with New Deal responses, the end of isolationism, wartime mobilization, and the experiences of marginalized Americans."};
const C=[
["CS 19","Stock speculation","Risky purchasing of shares in hopes of rapid profit, often using borrowed money","An investor buys shares with little cash and assumes prices can only rise",SRC.dep],
["CS 19","Buying on margin","Purchasing stock with borrowed money while paying only part of its price","A broker lends most of a stock's purchase price, magnifying gains and losses",SRC.dep],
["CS 19","Overproduction","Producing more goods than consumers can afford or want to buy","Factories and farms create surpluses while unsold inventories grow",SRC.dep],
["CS 19","Unequal distribution of wealth","Concentration of income that limits purchasing power for much of the population","Productivity rises but many families lack income to buy the goods produced",SRC.dep],
["CS 19","Bank failure","Collapse of a bank that can destroy uninsured deposits and reduce credit","Depositors rush to withdraw funds and the institution cannot meet demands",SRC.dep],
["CS 19","Stock Market Crash","The severe 1929 collapse in share prices that deepened economic fear","A rapid fall in Wall Street prices wipes out wealth and confidence",SRC.dep],
["CS 19","Great Depression","The prolonged economic collapse marked by unemployment, poverty, and declining production","Factories close, banks fail, and millions cannot find work",SRC.dep],
["CS 19","Unemployment","The condition of willing workers being unable to find jobs","A laid-off factory worker searches for work during a severe downturn",SRC.dep],
["CS 19","New Deal","Franklin Roosevelt's collection of relief, recovery, and reform programs","The federal government creates agencies to aid people and stabilize capitalism",SRC.newdeal],
["CS 19","Relief","Immediate assistance to people suffering during an economic emergency","A work program provides wages and food to families in crisis",SRC.newdeal],
["CS 19","Recovery","Policies intended to restart production, employment, and economic activity","Government spending and rules aim to revive business and demand",SRC.newdeal],
["CS 19","Reform","Long-term changes intended to prevent another economic collapse","New banking and securities rules seek to correct systemic weaknesses",SRC.newdeal],
["CS 19","Social Security Act","Federal law establishing old-age pensions and other social insurance","Workers and employers contribute to a national retirement-support system",SRC.newdeal],
["CS 19","FDIC","Federal insurance protecting qualifying bank deposits","A depositor is less likely to panic because the government backs the account",SRC.newdeal],
["CS 19","SEC","Federal agency regulating securities markets and requiring greater transparency","Wall Street firms face rules against fraud and misleading information",SRC.newdeal],
["CS 19","Public works","Government-funded construction that creates jobs and infrastructure","Unemployed workers are hired to build roads, parks, and public buildings",SRC.newdeal],
["CS 20","Isolationism","Policy of avoiding political and military entanglement in overseas conflicts","Congress tries to keep the nation outside wars spreading in Europe and Asia",SRC.road],
["CS 20","Neutrality Acts","1930s laws restricting trade and loans with nations at war","Federal law limits actions that might pull Americans into a foreign conflict",SRC.road],
["CS 20","Cash-and-carry","Policy allowing belligerents to buy U.S. goods if they paid cash and transported them","Britain purchases supplies but must use its own ships",SRC.road],
["CS 20","Lend-Lease Act","Program permitting the United States to provide military supplies to nations vital to its defense","Roosevelt sends weapons to Britain without requiring immediate payment",SRC.road],
["CS 20","Atlantic Charter","Roosevelt-Churchill statement of shared war aims and postwar principles","U.S. and British leaders outline a vision before America formally enters the war",SRC.road],
["CS 20","Pearl Harbor","Japanese attack that ended the major U.S. policy of staying out of World War II","A surprise attack on Hawaii leads Congress to declare war",SRC.road],
["CS 21","War Production Board","Agency coordinating conversion of industry to military production","An automobile plant is directed to manufacture tanks and aircraft parts",SRC.war],
["CS 21","Rationing","Government limits on consumer access to scarce wartime goods","Families use coupons to purchase gasoline, sugar, or meat",SRC.war],
["CS 21","Double V Campaign","African American campaign for victory over fascism abroad and racism at home","Black Americans support the war while demanding equal rights in the United States",SRC.war],
["CS 21","Japanese American internment","Forced wartime removal and confinement of Japanese Americans","Families are relocated from the West Coast without individualized proof of disloyalty",SRC.intern],
["CS 21","Navajo Code Talkers","American Indian Marines who used Navajo to transmit secure messages","A Native language becomes an effective military communications code",SRC.navajo],
["CS 21","Bracero Program","Wartime program bringing Mexican laborers to work temporarily in the United States","Agricultural employers fill labor shortages with contracted Mexican workers",SRC.war]
];
function opts(n,field){const a=[];for(let k=1;k<=3;k++)a.push(C[(n+k*7)%C.length][field]);return a}
function makeBase(kind){return C.map((c,n)=>{const answer=n%4;if(kind==="vocabulary"){const choices=opts(n,1);choices.splice(answer,0,c[1]);return{id:`v${String(n+1).padStart(2,"0")}`,cs:c[0],topic:c[1],prompt:`Which term matches this definition: ${c[2]}?`,choices,answer,source:c[4],where:"Use the source overview and locate the described policy, event, or condition.",explanation:`${c[1]} means ${c[2].charAt(0).toLowerCase()+c[2].slice(1)}.`,hint:`Look for the term connected to this clue: ${c[3]}.`}}const choices=opts(n,1);choices.splice(answer,0,c[1]);return{id:`${kind==="intro"?"i":"r"}${String(n+1).padStart(2,"0")}`,cs:c[0],topic:c[1],prompt:kind==="intro"?`According to the source, which development is described? ${c[2]}.`:`${c[3]}. Which term or development best applies?`,choices,answer,source:kind==="intro"?c[4]:"",where:kind==="intro"?"Scan for the policy, event, or condition described in the question.":"",explanation:`This is ${c[1]}: ${c[2].charAt(0).toLowerCase()+c[2].slice(1)}.`,hint:`Connect the scenario with ${c[1].split(" ")[0]} and its historical purpose.`}})}
const extra=[
["CS 19–21","Cause and Effect","Which chain is most accurate?","Financial weaknesses → Depression → New Deal expansion → larger federal role",["Pearl Harbor → stock speculation → Prohibition","New Deal → bank failures → 1929 crash","Rationing → Great Migration → isolationism"],"Economic collapse prompted unprecedented federal intervention."],
["CS 20–21","Policy Change","Which sequence best explains the end of U.S. isolationism?","Neutrality → aid to Allies → Pearl Harbor → declaration of war",["Pearl Harbor → Neutrality Acts → cash-and-carry","Lend-Lease → complete withdrawal → peace","Atlantic Charter → aid ends → alliance with Japan"],"The United States moved gradually toward aid before attack brought direct entry."],
["CS 21","Contradiction","Which wartime contradiction is clearest?","The nation fought tyranny abroad while interning Japanese Americans at home",["Rationing increased unlimited consumption","War production reduced factory output","Code Talkers weakened communications"],"Wartime defense of freedom coexisted with a major civil-liberties violation."],
["CS 19–21","Synthesis","Which thesis best summarizes Block 5?","Crisis expanded federal power, ended isolationism, and transformed society while exposing inequality",["The federal role steadily declined","World War II ended social conflict","Economic collapse had no political effect"],"The period linked economic emergency, global war, mobilization, and uneven freedom."]
];
function makeExtra(){return extra.map((e,j)=>{const n=28+j,answer=n%4,choices=e[4].slice();choices.splice(answer,0,e[3]);return{id:`r${n+1}`,cs:e[0],topic:e[1],prompt:e[2],choices,answer,source:"",where:"",explanation:e[5],hint:"Choose the answer that preserves the correct chronology and accounts for more than one content statement."}})}
window.BLOCK_QUESTIONS=mode==="intro"?makeBase("intro"):mode==="vocabulary"?makeBase("vocabulary"):[...makeBase("review"),...makeExtra()];
})();
