const W=window.WORKSHEET;
const $=id=>document.getElementById(id);
const state={answers:{},mastered:{},attempts:{},firstAttempts:{},events:[],questionSeconds:{},activeSeconds:0,awaySeconds:0,tabLeaves:0,status:'in_progress',startedAt:new Date().toISOString(),current:0,lastTick:Date.now()};
let timer=null,saveTimer=null,active=false;
function identity(){return{name:$('studentName').value.trim(),period:$('period').value,email:$('email').value.trim().toLowerCase()}}
function key(){return `${W.assignmentId}:${identity().email}`}
function valid(){let s=identity(),ok=s.name&&s.period&&/^\S+@\S+\.\S+$/.test(s.email);if(!ok)status('Enter your name, class period, and school email.');return ok}
function status(t){$('saveStatus').textContent=t}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function tick(){let now=Date.now(),sec=Math.min(15,Math.max(0,(now-state.lastTick)/1000));if(active){if(document.hidden)state.awaySeconds+=sec;else state.activeSeconds+=sec;let q=W.questions[state.current];if(q)state.questionSeconds[q.id]=(state.questionSeconds[q.id]||0)+sec}state.lastTick=now}
function packet(){tick();let s=identity(),score=W.questions.filter(q=>state.mastered[q.id]).length,attempts=Object.values(state.attempts).reduce((a,b)=>a+b,0);return{assignmentId:W.assignmentId,assignmentKey:W.assignmentId,assignmentTitle:W.title,studentName:s.name,name:s.name,period:s.period,email:s.email,answers:W.backend==='legacy'?Object.fromEntries(W.questions.map(q=>[q.id,state.answers[q.id]??''])):W.questions.map(q=>state.answers[q.id]??''),accepted:Object.fromEntries(W.questions.map(q=>[q.id,!!state.mastered[q.id]])),score,total:W.questions.length,percent:Math.round(score/W.questions.length*100),answerCount:Object.keys(state.answers).length,checkCount:attempts,firstAttemptCorrect:Object.values(state.firstAttempts).filter(Boolean).length,totalAttempts:attempts,accuracyPercent:attempts?Math.round(score/attempts*100):100,telemetry:{activeSeconds:state.activeSeconds,awaySeconds:state.awaySeconds,tabLeaves:state.tabLeaves,questionSeconds:state.questionSeconds,events:state.events},state:{...state,lastTick:undefined},status:state.status,savedAt:new Date().toISOString()}}
function saveLocal(){if(identity().email)localStorage.setItem(key(),JSON.stringify(packet()))}
function merge(d){if(!d)return;let resetAt=localStorage.getItem(key()+':resetAt');if(resetAt&&Date.parse(d.savedAt||0)<Date.parse(resetAt))return;let s=d.state||{};W.questions.forEach((q,i)=>{let ans=Array.isArray(d.answers)?d.answers[i]:(d.answers||{})[q.id];if(ans!==undefined&&ans!==''&&state.answers[q.id]===undefined)state.answers[q.id]=Number(ans);if(d.accepted?.[q.id]||s.mastered?.[q.id])state.mastered[q.id]=true});for(let [k,v] of Object.entries(s.attempts||{}))state.attempts[k]=Math.max(state.attempts[k]||0,Number(v)||0);Object.assign(state.firstAttempts,s.firstAttempts||{});state.activeSeconds=Math.max(state.activeSeconds,s.activeSeconds||0);state.awaySeconds=Math.max(state.awaySeconds,s.awaySeconds||0);state.events=[...state.events,...(s.events||[])].slice(-500);state.current=Math.max(0,W.questions.findIndex(q=>!state.mastered[q.id]));}
function restore(){if(!identity().email)return;try{merge(JSON.parse(localStorage.getItem(key())||'null'))}catch{}}
function render(){let q=W.questions[state.current];$('progress').textContent=`${state.current+1} of ${W.questions.length}`;$('accuracy').textContent=`${packet().accuracyPercent}%`;if(!q){complete();return}let letters='ABCD';$('question').innerHTML=`<div class="topic">${escapeHtml(q.topic||'Founding Documents')}</div><h2>${escapeHtml(q.prompt)}</h2><div class="choices">${q.choices.map((c,i)=>`<button class="choice" data-i="${i}"><b>${letters[i]}.</b> ${escapeHtml(c)}</button>`).join('')}</div><div id="feedback" role="status"></div><div class="source"><a href="${escapeHtml(q.source)}" target="_blank" rel="noopener">Open supporting source ↗</a><p><strong>Where to look:</strong> ${escapeHtml(q.where)}</p></div>`;document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>choose(Number(b.dataset.i),b));}
function choose(i,b){if(timer)return;let q=W.questions[state.current];state.answers[q.id]=i;state.attempts[q.id]=(state.attempts[q.id]||0)+1;if(state.firstAttempts[q.id]===undefined)state.firstAttempts[q.id]=i===q.answer;let fb=$('feedback');if(i===q.answer){state.mastered[q.id]=true;fb.className='good';fb.textContent=`Correct. ${q.explanation} Next question in four seconds.`;b.classList.add('correct');document.querySelectorAll('.choice').forEach(x=>x.disabled=true);state.events.push({type:'correct',id:q.id,at:new Date().toISOString()});saveLocal();queueSave();timer=setTimeout(()=>{timer=null;let n=W.questions.findIndex(x=>!state.mastered[x.id]);state.current=n<0?W.questions.length:n;render();window.scrollTo({top:0,behavior:'smooth'})},4000)}else{fb.className='bad';fb.textContent=`Not yet. ${q.hint}`;b.classList.add('wrong');setTimeout(()=>b.classList.remove('wrong'),600);state.events.push({type:'wrong',id:q.id,choice:i,at:new Date().toISOString()});saveLocal();queueSave()}$('accuracy').textContent=`${packet().accuracyPercent}%`}
function complete(){active=false;state.status='completed';$('question').innerHTML=`<h2>Mastery complete</h2><p>${escapeHtml(identity().name)} · Period ${escapeHtml(identity().period)}</p><p>${W.questions.length} of ${W.questions.length} mastered. ${packet().totalAttempts} attempts; ${packet().accuracyPercent}% attempt accuracy.</p><button id="submitBtn">Submit completed assignment</button><button id="restartBtn" class="secondary">Start over</button>`;$('submitBtn').onclick=submit;$('restartBtn').onclick=reset;saveLocal();queueSave()}
function start(){if(!valid())return;restore();active=true;$('identity').classList.add('hidden');$('work').classList.remove('hidden');state.current=W.questions.findIndex(q=>!state.mastered[q.id]);if(state.current<0)state.current=W.questions.length;render();queueSave()}
function reset(){let mail=identity().email;if(!mail)return status('Enter your school email first.');if(!confirm('Start over? Answers saved on this device will be cleared. Your teacher records remain.'))return;clearTimeout(timer);clearTimeout(saveTimer);localStorage.removeItem(key());localStorage.setItem(key()+':resetAt',new Date().toISOString());location.reload()}
function queueSave(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>cloudSave(false),800)}
async function cloudSave(manual){if(!valid())return;saveLocal();try{await fetch(W.scriptUrl,W.backend==='legacy'?{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'save',...packet()})}:{method:'POST',mode:'no-cors',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({action:state.status==='submitted'?'submit':'save',payload:JSON.stringify(packet())})});status('Saved on this device; copy sent to your teacher.')}catch{status('Saved on this device. Teacher copy could not be sent.')}}
function loadCloud(){if(!valid())return;let cb='load'+Date.now(),s=document.createElement('script'),done=false;let timeout=setTimeout(()=>{if(!done){status('Retrieval timed out.');cleanup()}},12000);function cleanup(){done=true;clearTimeout(timeout);delete window[cb];s.remove()}window[cb]=r=>{if(r?.found){merge(r.payload);saveLocal();status('Earlier answers merged.');if(active)render()}else status('No teacher draft found for this email.');cleanup()};s.onerror=()=>{status('Could not load teacher draft.');cleanup()};s.src=W.backend==='legacy'?`${W.scriptUrl}?action=load&assignmentKey=${encodeURIComponent(W.assignmentId)}&email=${encodeURIComponent(identity().email)}&callback=${cb}`:`${W.scriptUrl}?action=retrieve&assignmentId=${encodeURIComponent(W.assignmentId)}&email=${encodeURIComponent(identity().email)}&callback=${cb}`;document.body.appendChild(s)}
async function submit(){if(!valid())return;state.status='submitted';await cloudSave(true);$('submitBtn').disabled=true;status('Submission sent. Keep this completion screen visible.')}
function init(){$('title').textContent=W.title;$('description').textContent=W.description;$('total').textContent=W.questions.length;$('startBtn').onclick=start;$('loadBtn').onclick=loadCloud;$('saveBtn').onclick=()=>cloudSave(true);$('resetBtn').onclick=reset;document.addEventListener('visibilitychange',()=>{tick();if(document.hidden)state.tabLeaves++;state.events.push({type:document.hidden?'leave':'return',at:new Date().toISOString()})});for(let type of ['copy','paste'])document.addEventListener(type,()=>state.events.push({type,id:W.questions[state.current]?.id||'',at:new Date().toISOString()}));setInterval(()=>{tick();if(active)saveLocal()},1000)}init();
