(function(){
const SP="https://history.state.gov/milestones/1866-1898/spanish-american-war",BIG="https://history.state.gov/milestones/1899-1913/roosevelt-and-monroe-doctrine",WWI="https://history.state.gov/milestones/1914-1920/wwi",PTS="https://www.archives.gov/milestone-documents/president-woodrow-wilsons-14-points",LEAGUE="https://history.state.gov/milestones/1914-1920/league",KELLOGG="https://history.state.gov/milestones/1921-1936/kellogg";
const q=(id,cs,topic,prompt,choices,answer,source,where,explanation,hint)=>({id,cs,topic,prompt,choices,answer,source,where,explanation,hint});
window.BLOCK_CONFIG={assignmentKey:"AS-B3-CS14-15-INTRO-2026",title:"Block 3 Intro — America Becomes a World Power",description:"CS 14–15 • Overseas expansion, the Spanish-American War, World War I, peacemaking, and isolationism.",practice:"Use linked historical sources to discover why the United States expanded overseas, entered World War I, gained world-power status, and then limited its international commitments."};
window.BLOCK_QUESTIONS=[
q("i01","CS 14","Motives for Expansion","Which factor helped push the United States toward overseas expansion in the late 1800s?",["Competition for markets and international prestige","A desire to end all foreign trade","The disappearance of naval technology","European withdrawal from every colony"],0,SP,"Read the opening background and identify U.S. strategic and economic interests.","Economic markets, prestige, naval power, and ideas of cultural superiority all encouraged expansion.","Look for a motive involving economic opportunity and international status."),
q("i02","CS 14","Naval Power","Why did expansionists support a larger modern navy?",["To replace Congress","To protect overseas trade and project American power","To prevent settlement in the West","To enforce isolation from world markets"],1,SP,"Look for strategic bases, Pacific power, and protection of U.S. interests.","A modern navy could protect trade routes, defend overseas interests, and project power.","Connect naval strength with trade routes and overseas influence."),
q("i03","CS 14","Cultural Superiority","What idea was often used to justify American expansion?",["All nations should avoid contact","Military power was unnecessary","Americans had a superior culture they should spread","Colonized peoples always requested U.S. rule"],2,SP,"Compare pro-expansion arguments with the era's assumptions about civilization and race.","Some Americans used ethnocentric ideas of cultural superiority to rationalize control over other peoples.","Which choice presents a belief—not a proven fact—about one culture being above others?"),
q("i04","CS 14","Annexation of Hawaii","Which strategic argument supported annexing Hawaii?",["It would end Pacific trade","It would return Hawaii to Spain","It would eliminate naval bases","It could serve as a base protecting U.S. interests in Asia"],3,SP,"Read the paragraph explaining why supporters considered Hawaii economically and strategically valuable.","Hawaii's Pacific location made it valuable for naval operations and trade with Asia.","Focus on Hawaii's geographic location in the Pacific."),
q("i05","CS 14","Spanish-American War","What immediate event sharply increased pressure for U.S. intervention in Cuba?",["The explosion of the USS Maine in Havana Harbor","The signing of the Treaty of Versailles","The Zimmermann Telegram","The creation of the League of Nations"],0,SP,"Read the background immediately before President McKinley requested authority to intervene.","The Maine's destruction intensified public anger and helped make war more likely.","Look for the 1898 event in Havana Harbor."),
q("i06","CS 14","Yellow Journalism","How did sensational newspaper coverage influence the crisis with Spain?",["It reduced public interest","It heightened anger and support for intervention","It proved Spain caused the Maine explosion","It ended Cuban resistance"],1,SP,"Read about American public outrage and the mounting pressure surrounding Cuba.","Sensational coverage magnified atrocities and anger, increasing popular support for intervention.","Think about how dramatic headlines can shape public opinion."),
q("i07","CS 14","Results of War","Which territory did Spain cede to the United States after the Spanish-American War?",["Hawaii","Cuba","Puerto Rico","Panama"],2,SP,"Read the paragraph describing the Treaty of Paris and the territories Spain ceded.","The peace settlement transferred Puerto Rico, Guam, and the Philippines to U.S. control.","Hawaii was annexed separately, and Cuba was not formally annexed."),
q("i08","CS 14","Pacific Power","How did victory in the Spanish-American War change the United States?",["It ended all U.S. activity in Asia","It returned the nation to colonial status","It eliminated interest in foreign markets","It established the United States as a Caribbean and Pacific power"],3,SP,"Read the first paragraph summarizing the war's international consequences.","Victory and new territories expanded American strategic reach in the Caribbean and Pacific.","Choose the answer describing greater—not less—international reach."),
q("i09","CS 14","Big Stick Diplomacy","What did Theodore Roosevelt's “Big Stick” approach emphasize?",["Negotiation backed by credible military power","Withdrawal from the Western Hemisphere","Economic aid without any pressure","A permanent alliance with every nation"],0,BIG,"Read how Roosevelt's assertive approach and regional-police role were described.","Big Stick diplomacy paired negotiation with the visible ability and willingness to use force.","Recall the phrase “speak softly and carry a big stick.”"),
q("i10","CS 14","Roosevelt Corollary","What role did the Roosevelt Corollary claim for the United States?",["A neutral observer in Europe","A regional police power in the Western Hemisphere","A member of the League of Nations","A colony of European creditors"],1,BIG,"Read the comparison between the Monroe Doctrine and the more assertive corollary.","The corollary asserted a U.S. right to intervene in certain Western Hemisphere disputes.","Look for the policy that justified intervention in nearby countries."),
q("i11","CS 14","World War I Entry","Which German action was a major cause of U.S. entry into World War I?",["Ending submarine warfare","Joining the League of Nations","Resuming unrestricted submarine warfare","Returning overseas territories"],2,WWI,"Read the opening paragraphs about Wilson's April 1917 request for war.","Unrestricted submarine attacks threatened American ships, trade, and lives.","Find the naval policy that attacked ships without warning."),
q("i12","CS 14","Zimmermann Telegram","What did Germany propose in the Zimmermann Telegram?",["A peace conference in Washington","An alliance between Britain and Mexico","An end to submarine warfare","A German-Mexican alliance against the United States"],3,WWI,"Read the section describing the intercepted telegram and Germany's offer to Mexico.","Germany sought Mexican support and promised help recovering territory lost to the United States.","Look for the message that directly threatened U.S. territory."),
q("i13","CS 14","American Mobilization","How did U.S. entry affect the Allied war effort?",["A large American army and navy helped the Allies achieve victory","It forced the Allies to surrender","It ended American industrial production","It removed U.S. influence from peace negotiations"],0,WWI,"Connect U.S. entry with the military and material strength available to the Allies.","American troops, naval power, supplies, and economic capacity strengthened the Allies.","Which option adds U.S. resources to the Allied side?"),
q("i14","CS 14","World-Power Status","Why did World War I strengthen the United States relative to Europe?",["The United States lost all industrial capacity","European nations had to spend resources rebuilding while U.S. power expanded","Europe gained every overseas market","The United States withdrew before fighting"],1,PTS,"Read the background on the war's conclusion and international peace planning.","European destruction and debt contrasted with growing American economic and military influence.","Compare postwar rebuilding needs in Europe with U.S. strength."),
q("i15","CS 14","Cause and Effect","Which sequence best explains U.S. emergence as a world power?",["Isolation → loss of trade → smaller navy","League membership → colonial rule → neutrality","Overseas expansion → victory over Spain → major role in World War I","Treaty rejection → end of industry → European control"],2,SP,"Trace the page from expansion and war to new strategic influence.","Expansion, the Spanish-American War, and participation in World War I progressively increased U.S. power.","Put the three major CS 14 developments in chronological order."),
q("i16","CS 15","Fourteen Points","What was Wilson's main purpose in presenting the Fourteen Points?",["To acquire Spanish colonies","To punish Germany as severely as possible","To create secret military treaties","To offer principles for a lasting peace after World War I"],3,PTS,"Read the introductory paragraphs describing the speech as a blueprint for world peace.","Wilson proposed a peace program intended to address causes of war and prevent another conflict.","Look for a postwar peace plan rather than a wartime conquest plan."),
q("i17","CS 15","Open Diplomacy","Which Fourteen Points proposal addressed secret alliances and agreements?",["Open covenants openly arrived at","Permanent colonial expansion","Unlimited national armaments","Economic barriers between nations"],0,PTS,"Read Point I.","Wilson believed open diplomacy would reduce suspicion and hidden commitments.","The first point directly contrasts open diplomacy with secret agreements."),
q("i18","CS 15","Arms Limitation","Which proposal was intended to reduce the ability of nations to wage war?",["Higher tariffs","Reduction of national armaments","More secret treaties","Greater colonial competition"],1,PTS,"Read Point IV.","Wilson called for armaments to be reduced to the lowest level consistent with safety.","Find the point about weapons and military forces."),
q("i19","CS 15","Collective Security","What was the purpose of Wilson's proposed association of nations?",["To divide Germany into colonies","To expand U.S. territory","To protect the independence and territory of member nations collectively","To place Europe under U.S. rule"],2,PTS,"Read Point XIV and the explanation of the future League of Nations.","The proposed organization would use collective commitments to protect member states and preserve peace.","Look for nations promising mutual protection."),
q("i20","CS 15","Treaty of Versailles","How did the final Treaty of Versailles compare with Wilson's plan?",["It adopted every point exactly","It ignored the League idea entirely","It treated Germany more gently than Wilson proposed","It included a League but also punitive terms Wilson had not emphasized"],3,PTS,"Read the paragraphs explaining what Allied leaders kept and rejected from the Fourteen Points.","The treaty created the League but included punitive provisions shaped by Allied demands against Germany.","Separate Wilson's League proposal from the treaty's punishment of Germany."),
q("i21","CS 15","Treaty Ratification","Why did the Treaty of Versailles fail in the United States?",["The Senate refused to provide the required approval","The president vetoed it","The Supreme Court canceled it","Germany joined the Senate"],0,LEAGUE,"Read the section describing the Senate debate and votes on the treaty.","The Constitution requires Senate consent to treaties, and the necessary approval was not obtained.","Which branch gives advice and consent on treaties?"),
q("i22","CS 15","League Opposition","What did many opponents fear about League membership?",["It would eliminate international cooperation","It could pull the United States into foreign conflicts","It would prevent European rebuilding","It would ban all U.S. trade"],1,LEAGUE,"Find the arguments about collective-security obligations and congressional control over war.","Critics feared League commitments could entangle the United States in wars without sufficient independent choice.","Focus on the objection involving future military commitments."),
q("i23","CS 15","Reservationists","What change did Senator Henry Cabot Lodge and other reservationists seek?",["Immediate war with Germany","Abolition of the Senate","Conditions protecting U.S. authority before accepting the treaty","Permanent U.S. occupation of Europe"],2,LEAGUE,"Read about reservations proposed during the Senate treaty debate.","Reservationists wanted the treaty modified or interpreted to protect congressional and national authority.","They did not necessarily reject all cooperation; they wanted conditions."),
q("i24","CS 15","League Outcome","What was the result of the treaty debate for the United States?",["It led the League permanently","It annexed European territory","It signed the treaty without changes","It did not ratify the treaty or join the League of Nations"],3,PTS,"Read the paragraph explaining the Senate outcome and U.S. membership.","The United States stayed outside the League after the Senate failed to ratify the treaty.","The president supported membership, but the Senate outcome controlled ratification."),
q("i25","CS 15","Isolationism","What does isolationism mean in this postwar context?",["Limiting political and military involvement in foreign affairs","Ending all immigration permanently","Refusing every international trade agreement","Avoiding all communication with other nations"],0,KELLOGG,"Read how the United States avoided binding political commitments while still participating in selected diplomacy.","Postwar isolationism meant limiting entangling political and military commitments, not total separation from the world.","Do not confuse isolationism with ending every form of trade or diplomacy."),
q("i26","CS 15","Arms-Limitation Efforts","Why did the United States support arms-limitation agreements after World War I?",["To prepare for immediate conquest","To reduce the risk and cost of another major war","To create more secret alliances","To restore German submarine warfare"],1,KELLOGG,"Read the discussion of postwar peace efforts and limiting armaments.","Arms-limitation diplomacy sought to prevent costly arms races and reduce the likelihood of another war.","Connect the policy to Americans' desire to avoid another world war."),
q("i27","CS 15","Kellogg-Briand Pact","What did the Kellogg-Briand Pact attempt to do?",["Create the League of Nations","Partition Germany","Renounce war as an instrument of national policy","Require U.S. military intervention"],2,KELLOGG,"Read the statement of what the signatory nations renounced.","The pact declared that nations should not use war as a tool of national policy.","Look for a treaty rejecting war itself."),
q("i28","CS 14–15","Historical Tension","Which statement best summarizes the tension in U.S. foreign policy after World War I?",["The nation had no global influence and wanted more colonies","The nation rejected peace efforts and demanded war","The nation joined every alliance while reducing trade","The nation was a world power but resisted permanent international commitments"],3,LEAGUE,"Connect U.S. postwar power with the Senate debate over the League.","The United States possessed great international power while many Americans opposed obligations that might entangle it abroad.","Combine the outcome of CS 14 with the policy shift in CS 15.")
];
})();
