(function(){
const SP="https://history.state.gov/milestones/1866-1898/spanish-american-war",BIG="https://history.state.gov/milestones/1899-1913/roosevelt-and-monroe-doctrine",WWI="https://history.state.gov/milestones/1914-1920/wwi",PTS="https://www.archives.gov/milestone-documents/president-woodrow-wilsons-14-points",LEAGUE="https://history.state.gov/milestones/1914-1920/league",KELLOGG="https://history.state.gov/milestones/1921-1936/kellogg",MAHAN="https://history.state.gov/milestones/1866-1898/mahan",YELLOW="https://history.state.gov/milestones/1866-1898/yellow-journalism",OPEN="https://history.state.gov/milestones/1899-1913/hay-and-china",CANAL="https://history.state.gov/milestones/1899-1913/panama-canal",NAVAL="https://history.state.gov/milestones/1921-1936/naval-conference",PARIS="https://history.state.gov/milestones/1914-1920/paris-peace";
const q=(id,cs,topic,prompt,choices,answer,source,where,explanation,hint)=>({id,cs,topic,prompt,choices,answer,source,where,explanation,hint});
window.BLOCK_CONFIG={assignmentKey:"AS-B3-CS14-15-INTRO-2026-v3",title:"Block 3 Intro — America Becomes a World Power",description:"CS 14–15 • Overseas expansion, the Spanish-American War, World War I, peacemaking, and isolationism.",practice:"Use linked historical sources to discover why the United States expanded overseas, entered World War I, gained world-power status, and then limited its international commitments."};
window.BLOCK_QUESTIONS=[
q("i01","CS 14","Motives for Expansion","Which factor helped push the United States toward overseas expansion in the late 1800s?",["Access to overseas markets","A desire to end all foreign trade","The disappearance of naval technology","European withdrawal from every colony"],0,SP,"Read the opening background and identify U.S. strategic and economic interests.","Economic markets, prestige, naval power, and ideas of cultural superiority all encouraged expansion.","Look for a motive involving economic opportunity and international status."),
q("i02","CS 14","Naval Power","Why did expansionists support a larger modern navy?",["To replace Congress","Protecting trade and projecting power","To prevent settlement in the West","To enforce isolation from world markets"],1,MAHAN,"Look for strategic bases, Pacific power, and protection of U.S. interests.","A modern navy could protect trade routes, defend overseas interests, and project power.","Connect naval strength with trade routes and overseas influence."),
q("i03","CS 14","Cultural Superiority","What idea was often used to justify American expansion?",["All nations should avoid contact","Military power was unnecessary","A belief in American cultural superiority","Colonized peoples always requested U.S. rule"],2,SP,"Compare pro-expansion arguments with the era's assumptions about civilization and race.","Some Americans used ethnocentric ideas of cultural superiority to rationalize control over other peoples.","Which choice presents a belief—not a proven fact—about one culture being above others?"),
q("i04","CS 14","Annexation of Hawaii","Which strategic argument supported annexing Hawaii?",["It would end Pacific trade","It would return Hawaii to Spain","It would eliminate naval bases","A Pacific base for Asian trade"],3,SP,"Read the paragraph explaining why supporters considered Hawaii economically and strategically valuable.","Hawaii's Pacific location made it valuable for naval operations and trade with Asia.","Focus on Hawaii's geographic location in the Pacific."),
q("i05","CS 14","Spanish-American War","What immediate event sharply increased pressure for U.S. intervention in Cuba?",["The USS Maine explosion in Havana","The signing of the Treaty of Versailles","The Zimmermann Telegram","The creation of the League of Nations"],0,SP,"Read the background immediately before President McKinley requested authority to intervene.","The Maine's destruction intensified public anger and helped make war more likely.","Look for the 1898 event in Havana Harbor."),
q("i06","CS 14","Yellow Journalism","How did sensational newspaper coverage influence the crisis with Spain?",["It reduced public interest","It increased support for intervention","It proved Spain caused the Maine explosion","It ended Cuban resistance"],1,YELLOW,"Read about American public outrage and the mounting pressure surrounding Cuba.","Sensational coverage magnified atrocities and anger, increasing popular support for intervention.","Think about how dramatic headlines can shape public opinion."),
q("i07","CS 14","Results of War","Which territory did Spain cede to the United States after the Spanish-American War?",["The Hawaiian Islands","The island of Cuba","Puerto Rico","The Panama Canal Zone"],2,SP,"Read the paragraph describing the Treaty of Paris and the territories Spain ceded.","The peace settlement transferred Puerto Rico, Guam, and the Philippines to U.S. control.","Hawaii was annexed separately, and Cuba was not formally annexed."),
q("i08","CS 14","Pacific Power","How did victory in the Spanish-American War change the United States?",["It ended all U.S. activity in Asia","It returned the nation to colonial status","It eliminated interest in foreign markets","It gained overseas influence"],3,SP,"Read the first paragraph summarizing the war's international consequences.","Victory and new territories expanded American strategic reach in the Caribbean and Pacific.","Choose the answer describing greater—not less—international reach."),
q("i09","CS 14","Big Stick Diplomacy","What did Theodore Roosevelt's “Big Stick” approach emphasize?",["Diplomacy backed by military strength","Withdrawal from the Western Hemisphere","Economic aid without any pressure","A permanent alliance with every nation"],0,BIG,"Read how Roosevelt's assertive approach and regional-police role were described.","Big Stick diplomacy paired negotiation with the visible ability and willingness to use force.","Recall the phrase “speak softly and carry a big stick.”"),
q("i10","CS 14","Roosevelt Corollary","What role did the Roosevelt Corollary claim for the United States?",["A neutral observer in Europe","A Western Hemisphere police role","A member of the League of Nations","A colony of European creditors"],1,BIG,"Read the comparison between the Monroe Doctrine and the more assertive corollary.","The corollary asserted a U.S. right to intervene in certain Western Hemisphere disputes.","Look for the policy that justified intervention in nearby countries."),
q("i11","CS 14","World War I Entry","Which German action was a major cause of U.S. entry into World War I?",["Ending submarine warfare","Joining the League of Nations","Submarine attacks on ships","Returning overseas territories"],2,WWI,"Read the opening paragraphs about Wilson's April 1917 request for war.","Unrestricted submarine attacks threatened American ships, trade, and lives.","Find the naval policy that attacked ships without warning."),
q("i12","CS 14","Zimmermann Telegram","What did Germany propose in the Zimmermann Telegram?",["A peace conference in Washington","An alliance between Britain and Mexico","An end to submarine warfare","An alliance with Mexico"],3,WWI,"Read the section describing the intercepted telegram and Germany's offer to Mexico.","Germany sought Mexican support and promised help recovering territory lost to the United States.","Look for the message that directly threatened U.S. territory."),
q("i13","CS 14","American Mobilization","How did U.S. entry affect the Allied war effort?",["American troops and supplies aided the Allies","It forced the Allies to surrender","It ended American industrial production","It removed U.S. influence from peace negotiations"],0,WWI,"Connect U.S. entry with the military and material strength available to the Allies.","American troops, naval power, supplies, and economic capacity strengthened the Allies.","Which option adds U.S. resources to the Allied side?"),
q("i14","CS 14","Postwar Influence","What showed growing U.S. influence after World War I?",["The United States withdrew from every peace discussion","Wilson helped draft the League covenant","European leaders refused to discuss Wilson’s peace plan","The United States became a colony of a European empire"],1,LEAGUE,"Find Wilson’s role in drafting the League covenant at the Paris Peace Conference.","Wilson joined other Allied leaders in drafting the League covenant.","Look for a direct role in setting the postwar peace terms."),
q("i15","CS 14","Cause and Effect","Which sequence best explains U.S. emergence as a world power?",["Isolation → loss of trade → smaller navy","League membership → colonial rule → neutrality","Expansion → war with Spain → World War I","Treaty rejection → end of industry → European control"],2,SP,"Trace the page from expansion and war to new strategic influence.","Expansion, the Spanish-American War, and participation in World War I progressively increased U.S. power.","Put the three major CS 14 developments in chronological order."),
q("i16","CS 15","Fourteen Points","What was Wilson's main purpose in presenting the Fourteen Points?",["To acquire Spanish colonies","To punish Germany as severely as possible","To create secret military treaties","To outline a lasting peace"],3,PTS,"Read the introductory paragraphs describing the speech as a blueprint for world peace.","Wilson proposed a peace program intended to address causes of war and prevent another conflict.","Look for a postwar peace plan rather than a wartime conquest plan."),
q("i17","CS 15","Open Diplomacy","Which Fourteen Points proposal addressed secret alliances and agreements?",["Open agreements reached openly","Permanent colonial expansion","Unlimited national armaments","Economic barriers between nations"],0,PTS,"Read Point I.","Wilson believed open diplomacy would reduce suspicion and hidden commitments.","The first point directly contrasts open diplomacy with secret agreements."),
q("i18","CS 15","Arms Limitation","Which proposal was intended to reduce the ability of nations to wage war?",["Higher tariffs","Reducing national armaments","More secret treaties","Greater colonial competition"],1,PTS,"Read Point IV.","Wilson called for armaments to be reduced to the lowest level consistent with safety.","Find the point about weapons and military forces."),
q("i19","CS 15","Collective Security","What was the purpose of Wilson's proposed association of nations?",["To divide Germany into colonies","To expand U.S. territory","Mutual protection","To place Europe under U.S. rule"],2,PTS,"Read Point XIV and the explanation of the future League of Nations.","The proposed organization would use collective commitments to protect member states and preserve peace.","Look for nations promising mutual protection."),
q("i20","CS 15","Treaty of Versailles","How did the final Treaty of Versailles compare with Wilson's plan?",["It adopted every point exactly","It ignored the League idea entirely","It treated Germany more gently than Wilson proposed","It created a League and punished Germany"],3,PARIS,"Read the paragraphs explaining what Allied leaders kept and rejected from the Fourteen Points.","The treaty created the League but included punitive provisions shaped by Allied demands against Germany.","Separate Wilson's League proposal from the treaty's punishment of Germany."),
q("i21","CS 15","Treaty Ratification","Why did the Treaty of Versailles fail in the United States?",["The Senate rejected it","The president vetoed it","The Supreme Court canceled it","Germany joined the Senate"],0,LEAGUE,"Read the section describing the Senate debate and votes on the treaty.","The Constitution requires Senate consent to treaties, and the necessary approval was not obtained.","Which branch gives advice and consent on treaties?"),
q("i22","CS 15","League Opposition","What did many opponents fear about League membership?",["It would eliminate international cooperation","Involvement in future foreign wars","It would prevent European rebuilding","It would ban all U.S. trade"],1,LEAGUE,"Find the arguments about collective-security obligations and congressional control over war.","Critics feared League commitments could entangle the United States in wars without sufficient independent choice.","Focus on the objection involving future military commitments."),
q("i23","CS 15","Reservationists","What change did Senator Henry Cabot Lodge and other reservationists seek?",["Immediate war with Germany","Abolition of the Senate","Treaty reservations","Permanent U.S. occupation of Europe"],2,LEAGUE,"Read about reservations proposed during the Senate treaty debate.","Reservationists wanted the treaty modified or interpreted to protect congressional and national authority.","They did not necessarily reject all cooperation; they wanted conditions."),
q("i24","CS 15","League Outcome","What was the result of the treaty debate for the United States?",["It led the League permanently","It annexed European territory","It signed the treaty without changes","It stayed outside the League"],3,LEAGUE,"Read the paragraph explaining the Senate outcome and U.S. membership.","The United States stayed outside the League after the Senate failed to ratify the treaty.","The president supported membership, but the Senate outcome controlled ratification."),
q("i25","CS 15","Isolationism","What does isolationism mean in this postwar context?",["Avoiding foreign military commitments","Ending all immigration permanently","Refusing every international trade agreement","Avoiding all communication with other nations"],0,KELLOGG,"Read how the United States avoided binding political commitments while still participating in selected diplomacy.","Postwar isolationism meant limiting entangling political and military commitments, not total separation from the world.","Do not confuse isolationism with ending every form of trade or diplomacy."),
q("i26","CS 15","Arms-Limitation Efforts","Why did the United States support arms-limitation agreements after World War I?",["To prepare for immediate conquest","To limit future arms races","To create more secret alliances","To restore German submarine warfare"],1,NAVAL,"Read the discussion of postwar peace efforts and limiting armaments.","Arms-limitation diplomacy sought to prevent costly arms races and reduce the likelihood of another war.","Connect the policy to Americans' desire to avoid another world war."),
q("i27","CS 15","Kellogg-Briand Pact","What did the Kellogg-Briand Pact attempt to do?",["Create the League of Nations","Partition Germany","Renounce war as national policy","Require U.S. military intervention"],2,KELLOGG,"Read the statement of what the signatory nations renounced.","The pact declared that nations should not use war as a tool of national policy.","Look for a treaty rejecting war itself."),
q("i28","CS 14–15","Historical Tension","Which statement best summarizes the tension in U.S. foreign policy after World War I?",["The nation had no global influence and wanted more colonies","The nation rejected peace efforts and demanded war","The nation joined every alliance while reducing trade","Global power with limited foreign commitments"],3,LEAGUE,"Connect U.S. postwar power with the Senate debate over the League.","The United States possessed great international power while many Americans opposed obligations that might entangle it abroad.","Combine the outcome of CS 14 with the policy shift in CS 15.")
];

// Keep option and question order stable across reloads so saved answer indexes remain meaningful.
const extra=[
q("i29","CS 14","Sea Power","According to Mahan, why were overseas naval bases useful?",["Fuel stops for trade and naval ships","They made ships unnecessary","They prevented merchant vessels from traveling","They replaced all land-based industry"],0,MAHAN,"Read the discussion of coaling stations and international markets.","Bases extended the reach of American trade and naval forces.","What would a ship need far from home?"),
q("i30","CS 14","Hawaii","Why did Hawaii matter to U.S. expansion into Asia?",["It bordered China by land","A Pacific stop for trade ships","It belonged to Spain after the war","It ended all U.S. trade with Japan"],1,MAHAN,"Find Hawaii in the discussion of Pacific trade and naval strategy.","Hawaii provided a strategically placed Pacific stop.","Use its location to explain the economic interest."),
q("i31","CS 14","Cuba","Before the war, what was happening in Cuba?",["Cubans rebelled against Spain","A German invasion of the island","A League of Nations election","A U.S. civil war"],0,SP,"Read the paragraph on Cuban revolutionaries in 1895–1898.","Cubans fought to gain independence from Spain.","Identify who governed Cuba before 1898."),
q("i32","CS 14","Cuba's Status","Which comparison correctly describes Cuba and Puerto Rico after the war?",["Both were annexed as U.S. states","Spain retained both islands","Spain relinquished Cuba but ceded Puerto Rico","Cuba was ceded to Germany while Puerto Rico joined the League"],2,SP,"Read the first paragraph and the congressional resolution about annexing Cuba.","Spain relinquished Cuba while ceding Puerto Rico.","The treaty used different language for the two islands."),
q("i33","CS 14","Evidence and Inference","A headline blames Spain for the Maine explosion before investigators establish a cause. What should a historian conclude?",["The headline proves Spanish responsibility","It shows pressure, not proof of the cause","The war had already ended","The source proves Cuba was annexed"],1,YELLOW,"Read the discussion of the Maine and newspaper influence.","Press claims can influence opinion without proving causation.","Separate a newspaper's claim from verified evidence."),
q("i34","CS 14","Open Door","What economic goal did the Open Door policy pursue in China?",["Exclusive American ownership of China","Equal access to trade in China","An end to all Asian trade","A military alliance with Spain"],1,OPEN,"Read Hay's argument for equal access to commerce.","The United States sought equal trading opportunity.","Focus on access to markets."),
q("i35","CS 14","Open Door Cause","Why would U.S. businesses favor an Open Door policy?",["It kept Chinese markets open to U.S. trade","It closed Chinese ports to all American goods","It transferred China to U.S. control","It removed the need for foreign trade"],0,OPEN,"Find how Hay connected access in China to American traders.","Equal access could benefit U.S. commerce.","Think about the impact of exclusive trade zones."),
q("i36","CS 14","Panama Canal","What practical advantage did a canal across Panama provide?",["A shorter Atlantic-to-Pacific sea route","It ended the need for a navy","It joined North America to Europe by rail","It prevented ships from reaching Asia"],0,CANAL,"Read the opening explanation of why a canal route mattered.","Ships could move between oceans without rounding South America.","Compare the two ocean routes."),
q("i37","CS 14","Regional Power","Why did Roosevelt worry about European creditors intervening in the Caribbean?",["European intervention over debts","They demanded a League seat for Cuba","They planned to return Hawaii to Spain","They opposed construction of every navy"],0,BIG,"Read the Venezuela example just before the explanation of the corollary.","Roosevelt sought to keep European powers from using debt disputes to intervene nearby.","Look for the link between debts and foreign intervention."),
q("i38","CS 14","Policy Change","How did the Roosevelt Corollary extend the Monroe Doctrine?",["It reversed the policy and welcomed European colonies","It gave the League power over the Americas","It asserted a U.S. right to intervene nearby","It required withdrawal from Caribbean affairs"],2,BIG,"Compare the older passive warning with Roosevelt's regional police role.","The corollary claimed an active right to intervene.","Identify the move from warning to action."),
q("i39","CS 14","Neutrality and War","Which development most directly shifted the U.S. toward entering World War I in 1917?",["Renewed German submarine attacks","Creation of the League of Nations","The 1898 annexation of Hawaii","The 1928 Kellogg-Briand Pact"],0,WWI,"Read the 1917 sequence before Congress declared war.","Renewed unrestricted submarine warfare threatened U.S. ships and citizens.","Focus on the action that happened in 1917."),
q("i40","CS 14","Threat Assessment","Why did the Zimmermann Telegram add to U.S. concerns?",["It promised Germany would defend American borders","Germany sought an alliance with Mexico","It announced that the war had ended","It made the United States a League member"],1,WWI,"Read what Germany offered Mexico in the intercepted message.","Germany sought an alliance that threatened U.S. territory.","Identify the proposed partner and target."),
q("i41","CS 15","Fourteen Points","Which proposal would most directly reduce trade barriers after the war?",["Free navigation of the seas","Lower barriers to trade","A general association of nations","Reduction of armaments"],1,PTS,"Read Point III and distinguish it from Points II, IV, and XIV.","Point III called for fewer economic barriers and fair trade.","Find the point about commerce rather than military forces."),
q("i42","CS 15","Self-Determination","Which idea fits Wilson's approach to postwar territorial settlements?",["Ignore the people who live in disputed territories","Consider the wishes of affected populations","Give every territory to the largest empire","Make every colony an American state"],1,PTS,"Read the principles on colonial claims and European boundaries.","Wilson argued that populations' interests should matter in settlements.","Look for the people affected by a boundary."),
q("i43","CS 15","Treaty Compromise","Why did Wilson accept provisions that differed from parts of his Fourteen Points?",["He compromised to secure the League","Germany wrote the entire treaty without the Allies","The Senate drafted the peace agreement in Paris","He had abandoned the idea of international cooperation"],0,PARIS,"Read the negotiations and the disagreement among Allied leaders.","Wilson compromised on some terms while pursuing the League.","What did Wilson most want included in the settlement?"),
q("i44","CS 15","Senate Debate","A senator supports a peace organization but fears its commitments could bypass Congress's war powers. Which position is closest?",["Unqualified support for every League obligation","Opposition to all contact with Europe","Accept the treaty with reservations","A demand to annex Germany"],2,LEAGUE,"Read Lodge's concerns about obligations and U.S. interests.","Reservations sought limits on the commitments the nation would accept.","The senator wants conditions, not a total ban."),
q("i45","CS 15","Diplomacy Despite Isolation","What does U.S. participation in the Washington Naval Conference show?",["The U.S. still joined specific peace talks","The United States had joined the League secretly","The country had ended international trade","The United States wanted an unlimited naval arms race"],0,NAVAL,"Read who called the conference and what the participants discussed.","The United States negotiated arms limits while staying outside the League.","Distinguish a specific agreement from permanent membership.")
];
window.BLOCK_QUESTIONS.push(...extra);
function hash(str){let h=2166136261;for(const ch of str){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
let seed=Number(localStorage.getItem(window.BLOCK_CONFIG.assignmentKey+"|shuffle"));
if(!seed){seed=Math.floor(Math.random()*4294967295)||1;localStorage.setItem(window.BLOCK_CONFIG.assignmentKey+"|shuffle",String(seed))}
function random(){seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;return(seed>>>0)/4294967296}
function shuffle(a){a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
const ordered=shuffle(window.BLOCK_QUESTIONS),positions=shuffle(Array.from({length:ordered.length},(_,i)=>i%4));
window.BLOCK_QUESTIONS=ordered.map((item,n)=>{
  const correct=item.choices[item.answer],wrong=shuffle(item.choices.filter((_,i)=>i!==item.answer));
  const choices=wrong.slice();choices.splice(positions[n],0,correct);
  return{...item,choices,answer:positions[n]};
});
})();
