const APPS_SCRIPT_URL="https://script.google.com/macros/s/AKfycbyMW_yopi36jQkM9rx09Qa6yPZJDGRVCLCLfQmvJZzLk0eo2ZMT2frGzYp9_LZzq40wHg/exec",ASSIGNMENT_KEY="AS-B2-CS6-7-REVIEW-2026";
const questions=window.BLOCK_QUESTIONS;
questions.sort(()=>Math.random()-.5);
const state={answers:{},mastered:{},attempts:{},wrongTotal:0,firstStart:new Date().toISOString(),sessions:1,activeSeconds:0,awaySeconds:0,tabLeaves:0,events:[],questionSeconds:{},currentQuestion:null,lastTick:Date.now(),status:"in progress"};const $=id=>document.getElementById(id),storageKey=()=>`${ASSIGNMENT_KEY}|${$('email').value.trim().toLowerCase()}`;
function render(){$('totalCount').textContent=questions.length;$('questions').innerHTML=questions.map((x,n)=>`<article class="question" id="card-${x.id}"><div class="qtop"><span class="qnum">Question ${n+1}</span><span class="cs">${x.cs}</span></div><div class="prompt">${x.prompt}</div><div class="choices">${x.choices.map((c,i)=>`<label class="choice"><input type="radio" name="${x.id}" value="${i}"> <span>${c}</span></label>`).join('')}</div><div class="check-row"><button data-check="${x.id}">Check answer</button></div><div class="feedback" id="fb-${x.id}"></div></article>`).join('');document.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>check(b.dataset.check));document.querySelectorAll('.question').forEach(c=>c.onfocusin=()=>state.currentQuestion=c.id.slice(5));restoreLocal();update()}
function check(id){const x=questions.find(v=>v.id===id),p=document.querySelector(`input[name="${id}"]:checked`),f=$(`fb-${id}`);if(!p){f.className='feedback hint';f.textContent='Choose an answer first.';return}const v=+p.value;state.answers[id]=v;state.attempts[id]=(state.attempts[id]||0)+1;if(v===x.answer){state.mastered[id]=true;f.className='feedback good';f.innerHTML=`<strong>Correct.</strong> ${x.explanation}`;const c=$(`card-${id}`);c.classList.add('mastered');c.querySelectorAll('input,button').forEach(e=>e.disabled=true)}else{state.wrongTotal++;f.className='feedback bad';f.innerHTML=`<strong>Not yet.</strong> Hint: ${x.hint}`}saveLocal();update();queueCloudSave()}
function update(){const m=Object.keys(state.mastered).filter(k=>state.mastered[k]).length,a=Object.values(state.attempts).reduce((s,v)=>s+v,0);$('masteredCount').textContent=m;$('attemptCount').textContent=a;$('barFill').style.width=`${m/questions.length*100}%`;$('submitBtn').disabled=m!==questions.length}
function student(){return{name:$('studentName').value.trim(),period:$('period').value,email:$('email').value.trim().toLowerCase()}}function payload(){tick();return{assignmentKey:ASSIGNMENT_KEY,student:student(),state,answers:state.answers,mastered:state.mastered,score:Object.keys(state.mastered).length,total:questions.length,percent:Math.round(Object.keys(state.mastered).length/questions.length*100),answerCount:Object.keys(state.answers).length,wrongAttempts:state.wrongTotal,updatedAt:new Date().toISOString()}}
function saveLocal(){if($('email').value.trim())localStorage.setItem(storageKey(),JSON.stringify(payload()))}function restoreLocal(){const r=localStorage.getItem(storageKey());if(r)try{mergeDraft(JSON.parse(r));$('saveStatus').textContent='Local draft restored.'}catch{}}
function mergeDraft(d){const s=d.state||d;if(!d)return;for(const[k,v]of Object.entries(s.answers||d.answers||{}))if(state.answers[k]===undefined||state.answers[k]==='')state.answers[k]=v;Object.assign(state.mastered,s.mastered||d.mastered||{});for(const[k,v]of Object.entries(s.attempts||{}))state.attempts[k]=Math.max(state.attempts[k]||0,v||0);state.wrongTotal=Math.max(state.wrongTotal,s.wrongTotal||d.wrongAttempts||0);state.firstStart=s.firstStart||state.firstStart;applyState()}
function applyState(){questions.forEach(x=>{if(state.answers[x.id]!==undefined){const e=document.querySelector(`input[name="${x.id}"][value="${state.answers[x.id]}"]`);if(e)e.checked=true}if(state.mastered[x.id]){const c=$(`card-${x.id}`),f=$(`fb-${x.id}`);c.classList.add('mastered');c.querySelectorAll('input,button').forEach(e=>e.disabled=true);f.className='feedback good';f.innerHTML=`<strong>Correct.</strong> ${x.explanation}`}});update()}
let saveTimer;function queueCloudSave(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>cloudSave(false),900)}async function cloudSave(manual){if(!valid(false)||APPS_SCRIPT_URL.startsWith('PASTE_')){if(manual)$('saveStatus').textContent=APPS_SCRIPT_URL.startsWith('PASTE_')?'Saved on this device. Add the Apps Script URL for cloud saving.':'Enter name, period, and school email.';return}saveLocal();try{await fetch(APPS_SCRIPT_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({action:'save',payload:JSON.stringify(payload())})});$('saveStatus').textContent='Saved on this device and sent to your teacher draft.'}catch{$('saveStatus').textContent='Saved on this device. Cloud save could not be confirmed.'}}
function loadCloud(){if(!valid(true)||APPS_SCRIPT_URL.startsWith('PASTE_'))return;const cb=`load_${Date.now()}`,s=document.createElement('script');window[cb]=r=>{try{if(r&&r.found)mergeDraft(r.payload);saveLocal();$('saveStatus').textContent=r&&r.found?'Previous work merged safely.':'No cloud draft was found.'}finally{delete window[cb];s.remove()}};s.src=`${APPS_SCRIPT_URL}?action=load&assignmentKey=${encodeURIComponent(ASSIGNMENT_KEY)}&email=${encodeURIComponent(student().email)}&callback=${cb}`;s.onerror=()=>{$('saveStatus').textContent='Could not load the cloud draft.';delete window[cb];s.remove()};document.body.appendChild(s)}function valid(show=true){const x=student(),ok=x.name&&x.period&&/^\S+@\S+\.\S+$/.test(x.email);if(!ok&&show)$('saveStatus').textContent='Enter full name, period, and a valid school email first.';return ok}
function tick(){const n=Date.now(),sec=Math.max(0,Math.round((n-state.lastTick)/1000));if(document.hidden)state.awaySeconds+=sec;else state.activeSeconds+=sec;if(state.currentQuestion)state.questionSeconds[state.currentQuestion]=(state.questionSeconds[state.currentQuestion]||0)+sec;state.lastTick=n}setInterval(()=>{tick();saveLocal()},15000);document.addEventListener('visibilitychange',()=>{tick();if(document.hidden)state.tabLeaves++;state.events.push({type:document.hidden?'leave':'return',at:new Date().toISOString()})});document.addEventListener('copy',e=>state.events.push({type:'copy',question:e.target.closest('.question')?.id.slice(5)||'',at:new Date().toISOString()}));document.addEventListener('paste',e=>state.events.push({type:'paste',question:e.target.closest('.question')?.id.slice(5)||'',at:new Date().toISOString()}));$('studentName').onchange=restoreLocal;$('email').onchange=restoreLocal;$('period').onchange=saveLocal;$('saveBtn').onclick=()=>cloudSave(true);$('loadBtn').onclick=loadCloud;$('submitBtn').onclick=async()=>{if(!valid(true))return;state.status='submitted';state.submittedAt=new Date().toISOString();await cloudSave(true);$('submitStatus').textContent='Submitted successfully at 100% mastery.';$('submitBtn').disabled=true};render();
