(function(){
const CON="https://www.archives.gov/founding-docs/constitution-transcript";
const BIG="https://www.archives.gov/legislative/resources/education/reviewing-big-ideas";
const LOC="https://www.loc.gov/exhibits/creating-the-united-states/convention-and-ratification.html";
const HIST="https://www.archives.gov/founding-docs/more-perfect-union";
const BOR="https://www.archives.gov/founding-docs/bill-of-rights-transcript";
const q=(id,cs,prompt,choices,answer,source,where,explanation)=>({id,cs,prompt,choices,answer,source,where,explanation,hint:where});
window.BLOCK_QUESTIONS=[
q("v01","CS 6","What does popular sovereignty mean?",["Governmental authority comes from the people","Judges possess unlimited power","States may ignore the Constitution","Political office is inherited"],0,CON,"Read the Preamble and focus on who ordains and establishes the Constitution.","Popular sovereignty means the people are the source of governmental authority."),
q("v02","CS 6","Which term means government may exercise only powers granted to it and must obey the law?",["Ratification","Limited government","Commerce","Faction"],1,BIG,"Find the big idea describing restraints placed on governmental authority.","Limited government restricts public officials and institutions to lawful, granted powers."),
q("v03","CS 6","Which term describes dividing power between national and state governments?",["Due process","Popular sovereignty","Federalism","Ratification"],2,BIG,"Find the section explaining shared authority between levels of government.","Federalism divides power between national and state governments."),
q("v04","CS 6","Which term describes assigning legislative, executive, and judicial powers to different branches?",["Supremacy","Republic","Amendment","Separation of powers"],3,BIG,"Look for the big idea connected to Articles I, II, and III.","Separation of powers distributes major governmental functions among three branches."),
q("v05","CS 6","What are checks and balances?",["Ways each branch can restrain the others","Methods states use to leave the Union","Rules eliminating elections","Powers held only by local government"],0,BIG,"Read how the branches interact, including veto, advice and consent, and impeachment.","Checks and balances prevent one branch from exercising unchecked authority."),
q("v06","CS 6","What is a republic?",["Government by a hereditary monarch","Government in which people govern through elected representatives","Government controlled only by judges","Government without written law"],1,CON,"Connect “We the People” with Article I's elected House of Representatives.","In a republic, citizens exercise political power through representatives."),
q("v07","CS 6","What is a constitution?",["A temporary campaign promise","A court's decision in one case","A fundamental framework establishing and limiting government","A list of military commands"],2,CON,"Scan the Preamble and Articles I–VII to see the document's overall function.","A constitution creates the governmental framework, assigns powers, and places limits."),
q("v08","CS 6","What is an amendment?",["An executive order","A state election","A judicial trial","A formal addition or change to a constitution"],3,CON,"Go to Article V and then scan the amendments following Article VII.","An amendment formally adds to or changes constitutional text."),
q("v09","CS 6","What does legislative power involve?",["Making laws","Enforcing laws","Deciding court cases","Commanding state militias alone"],0,CON,"Read Article I, Section 1 and identify the power vested in Congress.","Legislative power is the authority to make laws."),
q("v10","CS 6","What does executive power involve?",["Writing constitutional amendments alone","Carrying out and enforcing laws","Serving as the final jury in trials","Selecting every member of Congress"],1,CON,"Read Article II, Section 1 and identify the branch led by the president.","Executive power is the authority to administer and enforce laws."),
q("v11","CS 6","What does judicial power involve?",["Collecting taxes","Commanding armies","Interpreting law while deciding cases","Approving every election result"],2,CON,"Read Article III and focus on cases and controversies.","Judicial power involves applying and interpreting law in legal cases."),
q("v12","CS 6","What is bicameralism?",["Division between state and national power","Rule by judges","Direct voting on every law","A legislature organized into two chambers"],3,CON,"Read Article I, Section 1 and identify the Senate and House.","Congress is bicameral because it contains two chambers."),
q("v13","CS 6","What is the Commerce Clause?",["Congress's power to regulate commerce with foreign nations, among states, and with tribes","The president's power to veto bills","The courts' power to appoint senators","The states' power to print national money"],0,CON,"In Article I, Section 8, locate the sentence beginning “To regulate Commerce.”","The Commerce Clause gives Congress authority over interstate and international commerce."),
q("v14","CS 6","What is the Necessary and Proper Clause?",["A ban on all implied powers","Authority for Congress to make laws needed to carry out its listed powers","A guarantee that every bill becomes law","A requirement that states approve federal taxes"],1,CON,"Read the final clause of Article I, Section 8.","The clause authorizes laws needed to execute Congress's enumerated powers."),
q("v15","CS 6","What is the Supremacy Clause?",["A rule making governors superior to Congress","A rule giving courts power to amend alone","The rule that the Constitution and valid federal laws prevail over conflicting state law","A rule ending state governments"],2,CON,"Read Article VI and find “supreme Law of the Land.”","The Supremacy Clause resolves conflicts in favor of the Constitution and valid federal law."),
q("v16","CS 6","What are enumerated powers?",["Powers denied to every government","Powers held only by citizens","Powers created by newspaper essays","Powers specifically listed in the Constitution"],3,CON,"Scan the list following “The Congress shall have Power” in Article I, Section 8.","Enumerated powers are expressly written into the Constitution."),
q("v17","CS 6","What are implied powers?",["Powers reasonably inferred from enumerated powers","Powers expressly prohibited to Congress","Powers belonging only to foreign nations","Powers created by state constitutions for Congress"],0,CON,"Connect an Article I, Section 8 listed power with the final Necessary and Proper Clause.","Implied powers are not stated word-for-word but are reasonably derived from granted powers."),
q("v18","CS 6","What is consent of the governed?",["Citizens must approve every individual law","Legitimate government depends on the people's agreement and authority","Courts govern without elections","Officials may act above the Constitution"],1,CON,"Connect “We the People” with the Constitution's election provisions.","Consent of the governed means political authority rests on the people's authorization."),
q("v19","CS 7","What is ratification?",["Writing a first draft","Repealing every prior law","Formal approval of a proposed constitution or amendment","Refusing to debate a proposal"],2,HIST,"Look for how state conventions made the proposed Constitution effective.","Ratification is the act of formally approving a proposed governing document."),
q("v20","CS 7","Who was a Federalist in the ratification debate?",["A supporter of the Articles who opposed all change","A person demanding return to British rule","A person opposing any union of states","A supporter of the proposed Constitution"],3,LOC,"Read why the Federalist Papers were written.","Federalists worked for ratification of the proposed Constitution."),
q("v21","CS 7","Who was an Anti-Federalist?",["An opponent of ratification who feared concentrated national power","A supporter of unlimited presidential power","An author of the Declaration's grievances","An official appointed under Article III"],0,HIST,"Read the section on opposition during ratification and demands for a bill of rights.","Anti-Federalists opposed ratification and emphasized dangers to state power and individual liberty."),
q("v22","CS 7","What were the Federalist Papers?",["The first ten amendments","Essays defending the Constitution and urging ratification","British laws taxing the colonies","Supreme Court opinions"],1,LOC,"Find the exhibit subsection titled “The Federalist Papers.”","The Federalist Papers were persuasive essays supporting ratification."),
q("v23","CS 7","What does the pseudonym Publius identify?",["The president of the Convention","The principal Anti-Federalist writer","The shared pen name used by Federalist Papers authors","The official title of Congress"],2,LOC,"Read the information accompanying the Federalist Papers and their anonymous publication.","Hamilton, Madison, and Jay published the essays under the name Publius."),
q("v24","CS 7","What is a standing army?",["Citizens called temporarily for jury duty","A group of elected lawmakers","A state constitutional convention","A permanent professional military force maintained in peacetime"],3,HIST,"Read Anti-Federalist concerns about military power in the ratification debate.","A standing army is a permanent military force, not one created only for a temporary emergency."),
q("v25","CS 7","What is an individual liberty?",["A protected personal freedom","A tax collected by Congress","A military alliance","A power belonging to a legislature"],0,BOR,"Scan Amendments I–VIII for protections held by individuals.","Individual liberties protect personal freedom from improper governmental interference."),
q("v26","CS 7","What is due process of law?",["The power to regulate commerce","Fair legal procedures government must follow before depriving a person of life, liberty, or property","A guarantee of acquittal","The right of officials to avoid trial"],1,BOR,"Read Amendment V and find “due process of law.”","Due process requires government to follow fair and established legal procedures."),
q("v27","CS 7","What does search and seizure mean in the Fourth Amendment?",["Congress debating a tax","Voters choosing representatives","Government examination or taking of a person, place, or property for evidence","States ratifying an amendment"],2,BOR,"Read Amendment IV and note the people, houses, papers, and effects it protects.","The term concerns government searches for and taking of people or property, constrained by the Fourth Amendment."),
q("v28","CS 7","What is the Bill of Rights?",["The seven original articles","The Federalist Papers","The list of powers in Article I","The first ten amendments protecting liberties and limiting government"],3,BOR,"Read the introductory note and the first ten amendments.","The Bill of Rights consists of the Constitution's first ten amendments.")
];
})();
