(function(){
const cfg={
  key:"AS-B4-CS16-18-REVIEW-2026",
  title:"Block 4 Comprehensive Review — Unrest and the Roaring Twenties",
  desc:"CS 16–18 • Forty application, cause-and-effect, comparison, and synthesis questions.",
  practice:"Apply the complete story of postwar tensions, new technology, mass culture, African American expression, women's political participation, and Prohibition."
};
window.BLOCK_CONFIG={assignmentKey:cfg.key,title:cfg.title,description:cfg.desc,practice:cfg.practice};
function build(rows){return rows.map((r,n)=>{const choices=r[5].slice(),answer=n%4;choices.splice(answer,0,r[4]);return{id:r[0],cs:r[1],topic:r[2],prompt:r[3],choices,answer,source:r[6]||"",where:r[7]||"",explanation:r[8],hint:r[9]}})}
const review=[
["r01","CS 16","Migration Causes","A Black family leaves Mississippi after racial violence and finds factory work in Chicago. Which explanation fits?","Push factors in the South and pull factors in the North drove the Great Migration",["Prohibition encouraged movement toward western farming communities","Radio broadcasts persuaded southern workers to leave agriculture","Immigration quotas created new jobs specifically for southern farmers"],"","","The example combines escape from discrimination with economic opportunity.","Identify both why they left and why they chose Chicago."],
["r02","CS 16","Urban Effects","Northern housing discrimination confines newcomers to crowded neighborhoods. What does this show?","Migration changed location but did not eliminate racism",["Northern cities immediately eliminated racial discrimination","Industrial employment guaranteed equal treatment in housing","Urban growth removed competition over jobs and neighborhoods"],"","","Racial barriers followed migrants into northern life.","Moving north did not guarantee equality."],
["r03","CS 16","Nativism","A politician blames immigrants for crime and demands nationality quotas. Which attitude is shown?","Nativism",["Collective bargaining","Modernism","Suffrage"],"","","The politician treats immigrants as threats and favors native-born people.","Focus on hostility to newcomers."],
["r04","CS 16","Quota Effects","Which group was most directly restricted by 1920s national-origins quotas?","Immigrants from southern and eastern Europe",["Native-born industrial workers in northern cities","Women entering politics after the 19th Amendment","African American artists of the Harlem Renaissance"],"","","Quotas were designed to reduce immigration from disfavored European regions.","Recall which newer immigrant groups nativists targeted."],
["r05","CS 16","Red Scare","Officials arrest immigrants because of suspected beliefs rather than proven crimes. Which tension is clearest?","National-security fear versus civil liberties",["Rural traditions versus increased automobile ownership","Jazz culture versus the expansion of radio broadcasting","Women's suffrage versus enforcement of Prohibition"],"","","Red Scare enforcement often sacrificed rights in the name of security.","Compare fear of subversion with due process."],
["r06","CS 16","Multiple Causes","Which combination best explains postwar unrest?","Racial tension, nativism, strikes, and fear of communism",["Rapid prosperity, open immigration, and declining labor conflict","Falling industrial output, fewer cities, and reduced immigration","Jazz, automobiles, commercial aviation, and motion pictures"],"","","Several racial, economic, and ideological conflicts converged.","Choose the multi-causal answer."],
["r07","CS 16","KKK","The revived Klan targets Black citizens, Catholics, Jews, and immigrants. What unites these actions?","Organized intolerance defending a narrow definition of American identity",["Organized support for religious and cultural pluralism in American life","A national campaign to expand civil liberties for minority groups","A reform movement designed to eliminate racial segregation by law"],"","","The Klan fused racism, religious prejudice, and nativism.","Look for exclusion across several groups."],
["r08","CS 16","Cause and Effect","Russian Revolution and violent strikes → public fear → raids and deportations. This sequence describes—","the First Red Scare",["the Harlem Renaissance","the repeal of Prohibition","the growth of mass production"],"","","Fear of revolution produced aggressive government action.","Connect Russia and suspected radicals."],
["r09","CS 17","Production","A factory divides automobile construction into simple repeated jobs. What result is most likely?","Faster mass production using more unskilled labor",["Slower production requiring more highly trained craft workers","Higher prices because each automobile becomes individually built","Less standardization as workers independently design each product"],"","","Assembly lines traded craft control for speed and volume.","Repeated specialized tasks increase output."],
["r10","CS 17","Consumer Change","Lower-priced automobiles become widely available. Which effect follows?","Greater mobility and changes in work, leisure, and settlement",["Less travel as families become increasingly tied to city centers","Reduced road construction as railroads replace personal transportation","Fewer suburbs because workers must live within walking distance of jobs"],"","","Affordable cars reshaped daily geography.","Think about how far people can travel."],
["r11","CS 17","Mass Culture","Families across the country hear the same radio program. This best demonstrates—","development of a shared mass culture",["collapse of long-distance communication networks","increased isolation of separate geographic regions","decline of national advertising and consumer markets"],"","","Broadcasting created common national experiences.","Many people receive one message simultaneously."],
["r12","CS 17","Advertising","Why did radio and magazines strengthen consumer culture?","They connected mass advertising with large audiences",["They prohibited companies from promoting national brand names","They reduced public exposure to information about consumer goods","They brought installment buying and consumer credit to an end"],"","","Media encouraged demand for mass-produced products.","Advertising needs an audience."],
["r13","CS 17","Uneven Prosperity","Why should historians qualify the phrase “Roaring Twenties prosperity”?","Benefits and improved living standards were not shared equally",["Technological innovation produced almost no economic improvement","Nearly every worker and farmer experienced the same level of wealth","Rapid urban growth stopped as Americans returned to rural communities"],"","","Many prospered, but racial, regional, and class inequalities persisted.","Avoid an absolute claim about everyone."],
["r14","CS 17","Cultural Conflict","Older Americans condemn movies and changing youth behavior. What caused the disagreement?","Modern mass culture challenged traditional social norms",["New technology eliminated most differences between generations","Traditional rural values disappeared immediately throughout the nation","Prohibition gained nearly universal acceptance among younger Americans"],"","","Rapid change often provoked resistance from traditionalists.","Contrast modernism with tradition."],
["r15","CS 17","Technology","Which innovation most directly created real-time national home audiences?","Commercial radio",["The skyscraper","The assembly line","Commercial aircraft"],"","","Radio broadcast the same news and entertainment into homes.","Which device transmitted sound immediately?"],
["r16","CS 17","Cause and Effect","Mass production → lower prices → more buyers → more advertising. This chain describes—","growth of consumer culture",["collapse of industrial production","the end of consumer credit","decline of national mass media"],"","","Efficient output and marketing reinforced mass consumption.","Follow the link from goods to purchasing."],
["r17","CS 18","Harlem Renaissance","A poet celebrates Black identity while exposing discrimination. Which movement is represented?","Harlem Renaissance",["First Red Scare","Nativist movement","National Prohibition"],"","","The movement joined cultural pride with criticism of injustice.","Look for Black art and literature."],
["r18","CS 18","Migration and Culture","How did the Great Migration help cause the Harlem Renaissance?","It concentrated Black communities and talent in northern cultural centers",["It prohibited jazz performances in major northern cities","It reduced the growth of African American urban communities","It weakened audiences for Black writers, musicians, and artists"],"","","Migration created vibrant communities supporting artists and institutions.","Population movement preceded cultural flowering."],
["r19","CS 18","Jazz","Jazz spreads from Black communities to national audiences through recordings and radio. This is—","cultural diffusion",["political deportation","legal segregation","immigration restriction"],"","","A cultural form moved from one community into broader society.","Diffusion means spread."],
["r20","CS 18","Suffrage","Which immediate political change followed the 19th Amendment?","Women could vote without sex being used as a constitutional basis for denial",["All forms of legal and economic discrimination against women immediately ended","National Prohibition was repealed as soon as women entered the electorate","Women immediately received equal wages in every occupation and industry"],"","","The amendment addressed voting, not every inequality.","Choose the precise constitutional effect."],
["r21","CS 18","Prohibition","A desired product is banned, but customers continue seeking it. What economic result is likely?","A profitable illegal market develops",["Demand for the prohibited product immediately disappears","Organized criminal groups lose an important source of revenue","Government enforcement becomes unnecessary because consumers comply"],"","","Persistent demand creates opportunity for illegal suppliers.","Think black market."],
["r22","CS 18","Policy Evaluation","Which evidence best supports calling Prohibition a mixed success?","Some drinking declined, but speakeasies and organized crime expanded",["Nearly every citizen obeyed the law throughout the Prohibition era","Federal and local governments made almost no effort to enforce the law","Demand for alcoholic beverages permanently disappeared across the nation"],"","","The policy produced both intended and unintended outcomes.","A mixed result contains success and failure."],
["r23","CS 18","Reform Limits","Why did Prohibition lack durable popular support?","Enforcement conflicts and widespread evasion weakened legitimacy",["Alcohol had virtually no consumers by the end of the decade","Organized crime disappeared because illegal markets were unprofitable","The constitutional amendment protected voting rather than regulating alcohol"],"","","A rule repeatedly ignored becomes difficult to sustain.","Consider compliance and enforceability."],
["r24","CS 18","Social Change","Which pairing correctly matches movement and result?","Women's suffrage—greater political participation",["Red Scare—expanded protections for suspected immigrant radicals","Nativism—greater acceptance of unrestricted immigration","Prohibition—permanent elimination of organized criminal activity"],"","","Voting rights widened women's formal political role.","Reject pairings that reverse actual effects."],
["r25","CS 16–18","Comparison","What did the Red Scare and Prohibition share?","Both encouraged government enforcement that produced civil-liberty or crime concerns",["Both directly expanded immigration from southern and eastern Europe","Both developed primarily from the spread of jazz and Black culture","Both guaranteed greater equality for groups facing discrimination"],"","","Each policy area showed unintended costs of moral or security enforcement.","Look for government power and unintended results."],
["r26","CS 16–18","Contradiction","Which contradiction best characterizes the decade?","Celebration of modern freedom coexisted with exclusion and repression",["Technological development largely stopped while cities continued to grow","Cultural creativity declined as Americans rejected music and motion pictures","Racial prejudice disappeared while immigration restrictions became less common"],"","","Modern consumer life and art grew alongside nativism and racial violence.","Choose the contrast."],
["r27","CS 16–18","Evidence","Which pair best demonstrates both cultural innovation and intolerance?","Harlem Renaissance and revived Ku Klux Klan",["Assembly-line production and widespread automobile ownership","Commercial radio broadcasting and talking motion pictures","Women's suffrage and the nationwide popularity of jazz music"],"","","One represents Black cultural achievement; the other organized hatred.","Find one positive cultural movement and one exclusionary movement."],
["r28","CS 16–18","Cause and Effect","Which development links technology to social tension?","Mass media spread modern values that challenged traditional beliefs",["Assembly-line factories brought long-distance communication to an end","Commercial aircraft directly caused states to create segregation laws","Automobile ownership produced the political fears of the First Red Scare"],"","","Communication technology accelerated exposure to new ideas.","Focus on ideas reaching broad audiences."],
["r29","CS 16–18","Historical Argument","Which thesis is strongest?","The 1920s combined economic modernization with unresolved racial and cultural conflict",["The decade can be understood almost entirely as a period of prosperity","Technological development largely solved racial and religious prejudice","Reform movements eliminated the social problems they attempted to address"],"","","A strong thesis accounts for multiple dimensions and contradictions.","Avoid one-sided absolutes."],
["r30","CS 16–18","Continuity","Which condition showed continuity with earlier eras?","Racial discrimination and violence persisted despite migration and cultural achievement",["Traditional social norms completely vanished during the decade","Immigration became increasingly unrestricted after World War I","Women lost the constitutional voting rights they had recently gained"],"","","Major changes did not erase longstanding racism.","Continuity means something persisted."],
["r31","CS 16–18","Change","Which development best represents change during the 1920s?","Mass media created shared national consumer culture",["Jim Crow segregation continued in much of the country","Racial prejudice remained a powerful force in American society","Nativist attitudes continued to influence immigration policy"],"","","Radio, film, and print expanded a national culture in new ways.","Choose the new development rather than persistence."],
["r32","CS 16–18","Synthesis","Which summary best fits Block 4?","Postwar fears produced exclusion while technology, migration, and reform transformed culture",["The nation experienced little social tension despite rapid economic change","Reform movements consistently achieved their goals without unintended effects","Economic and technological changes had little influence on American culture"],"","","The period's central story is simultaneous transformation and conflict.","Include CS 16, 17, and 18 in one claim."],
["r33","CS 16","Palmer Raids","Why are the Palmer Raids useful evidence when evaluating the First Red Scare?","They show how fear of radicalism led the government to arrest suspected radicals and threaten civil liberties",["They show how the government encouraged unrestricted immigration during a period of nativism","They demonstrate that organized labor completely ended political fears after World War I","They prove that racial violence disappeared as federal officials focused on communism"],"","","The raids targeted suspected radicals during intense fear of communist influence.","Connect government action, fear, and civil liberties."],
["r34","CS 16","Immigration Policy","How did nativism influence federal policy during the 1920s?","Congress adopted quota laws that sharply restricted immigration from selected regions",["Congress removed most restrictions and encouraged immigration from every European nation","The federal government transferred control of immigration policy entirely to individual states","National policy guaranteed equal immigration totals for every nation regardless of population"],"","","Nativist pressure translated anti-immigrant sentiment into federal restriction.","Look for the policy consequence of anti-immigrant attitudes."],
["r35","CS 17","Installment Buying","Why did installment buying help expand consumer culture in the 1920s?","It allowed consumers to obtain goods immediately and pay for them over time",["It required families to pay the entire price before receiving any product","It prevented businesses from advertising expensive mass-produced consumer goods","It reduced access to automobiles and appliances by eliminating consumer credit"],"","","Credit increased consumers' ability to purchase relatively expensive goods.","Think buy now and pay over time."],
["r36","CS 17","Automobile Effects","Which development was most directly encouraged by widespread automobile ownership?","Growth of roads, roadside businesses, suburbs, and greater personal mobility",["A return to isolated communities with fewer transportation connections","A decline in travel that reduced demand for hotels and service stations","The disappearance of residential development outside major urban centers"],"","","Automobiles changed where Americans lived, worked, traveled, and spent money.","Think beyond the car itself to the infrastructure around it."],
["r37","CS 18","Harlem Renaissance","Which statement best explains why the Harlem Renaissance mattered beyond Harlem?","Black writers, artists, and musicians influenced national culture while challenging stereotypes and racism",["The movement remained isolated and had little influence outside one New York neighborhood","Its primary goal was to support immigration quotas and other nativist political restrictions","Its artists generally avoided questions involving Black identity or racial discrimination"],"","","The movement combined cultural achievement with racial pride and wider influence.","Consider both cultural contribution and social meaning."],
["r38","CS 18","Women and Change","Which statement best describes the significance of the 19th Amendment?","It removed sex as a constitutional basis for denying voting rights and expanded women's formal political participation",["It immediately guaranteed complete social and economic equality for women in every state","It established national Prohibition and placed enforcement responsibility on women voters","It ended all state election rules and transferred control of voting entirely to Congress"],"","","The amendment was a major political change but did not erase every inequality.","Distinguish voting rights from broader equality."],
["r39","CS 18","Prohibition Consequences","Why could Prohibition strengthen organized crime even though its goal was social reform?","Continuing demand for alcohol created an illegal market that criminal organizations could supply for profit",["The amendment directly authorized criminal organizations to manufacture and sell alcoholic beverages","Demand for alcohol disappeared, forcing criminal groups to enter legal businesses for income","Federal enforcement eliminated smuggling and therefore increased profits from legal alcohol sales"],"","","A ban can create a black market when demand for the banned product remains.","Trace demand → illegal supply → profit."],
["r40","CS 16–18","Synthesis","A historian describes the 1920s as an era of both liberation and restriction. Which evidence best supports that interpretation?","Women's suffrage and Black cultural expression expanded while nativism, quotas, and racial intolerance also persisted",["Immigration became unrestricted while racial prejudice disappeared from American public life","Mass production declined while radio and motion pictures became less important to national culture","Prohibition ended organized crime while the Red Scare expanded protections for political dissent"],"","","The decade included expanded participation and cultural expression alongside powerful forms of exclusion.","Choose evidence showing both sides of the interpretation."]
];
window.BLOCK_QUESTIONS=build(review);
})();