(function(){
const q=(id,cs,topic,prompt,choices,answer,explanation,hint)=>({id,cs,topic,prompt,choices,answer,explanation,hint});
window.BLOCK_CONFIG={assignmentKey:"AS-B3-CS14-15-REVIEW-2026",title:"Block 3 Comprehensive Review — World Power and Isolationism",description:"CS 14–15 • Thirty-two scenario, cause-and-effect, comparison, and synthesis questions.",practice:"Apply the full Block 3 story: motives for expansion, the growth of U.S. power, entry into World War I, Wilsonian peacemaking, the treaty debate, and selective isolationism."};
window.BLOCK_QUESTIONS=[
q("r01","CS 14","Expansion Motives","An American business leader argues that factories need new overseas customers. Which motive for expansion is emphasized?",["Access to foreign markets","Avoidance of international trade","Reduction of naval strength","Opposition to industrial production"],0,"The argument connects industrial output with the economic search for overseas markets.","Focus on where businesses could sell surplus goods."),
q("r02","CS 14","Strategic Power","A senator supports acquiring an island because it can refuel naval vessels near Asian trade routes. Which motive is strongest?",["Humanitarian reform","Military and strategic advantage","Domestic urbanization","European isolation"],1,"The island's location would support naval operations and protect trade routes.","The key clues are naval vessels, refueling, and location."),
q("r03","CS 14","Cultural Superiority","A speaker claims the United States has a duty to impose its supposedly superior civilization on other peoples. This reflects—",["collective security","neutrality","cultural superiority used to justify imperialism","self-determination"],2,"Expansionists sometimes rationalized control through ethnocentric and racist assumptions.","Which concept ranks one culture above another?"),
q("r04","CS 14","Multiple Causes","Which combination best explains late-1800s U.S. expansion?",["Fewer markets, a weaker navy, and antiwar treaties","League membership, disarmament, and neutrality","Agricultural decline alone","Markets, prestige, naval growth, and cultural assumptions"],3,"Ohio's standard identifies several interacting economic, strategic, and ideological motives.","Choose the only answer containing multiple pro-expansion forces."),
q("r05","CS 14","Hawaii","Which cause-and-effect relationship involving Hawaii is most accurate?",["Its Pacific location encouraged annexation for trade and naval strategy","Its location made it useless for Asian trade","Annexation ended American Pacific influence","Spain transferred Hawaii in the Versailles Treaty"],0,"Hawaii's location made it valuable as a strategic base and commercial link.","Connect geography to naval and trade interests."),
q("r06","CS 14","Public Opinion","After a mysterious ship explosion, newspapers publish dramatic accusations before evidence is settled. What effect is most likely?",["Reduced public attention","Increased popular pressure for war","Immediate League membership","Automatic treaty ratification"],1,"Sensational reporting can intensify anger and interventionist sentiment.","How might emotionally charged headlines affect readers?"),
q("r07","CS 14","Spanish-American War","Which development most directly demonstrated that the United States had become a Pacific power?",["Refusal to build a navy","Withdrawal from all overseas trade","Acquisition of Guam and the Philippines","Rejection of the League of Nations"],2,"Territories and naval reach in the Pacific expanded U.S. strategic influence.","Identify the result located in the Pacific Ocean."),
q("r08","CS 14","War Results","Which conclusion is best supported by the outcome of the Spanish-American War?",["The United States abandoned the Caribbean","Spain expanded its Western Hemisphere empire","American overseas influence disappeared","Military victory accelerated U.S. emergence as an imperial world power"],3,"Victory brought overseas territories and a larger role in Caribbean and Pacific affairs.","Choose the option showing increased international power."),
q("r09","CS 14","Big Stick Diplomacy","A president negotiates with a nearby country while positioning warships offshore. Which policy does this resemble?",["Big Stick diplomacy","Isolationism","Self-determination","Disarmament"],0,"The scenario combines diplomacy with a visible threat of force.","Recall “speak softly” plus military capability."),
q("r10","CS 14","Roosevelt Corollary","What long-term effect followed from the Roosevelt Corollary?",["Europe became the regional police power","The United States used intervention to expand its Western Hemisphere influence","The United States joined the League","Latin American nations gained control of Congress"],1,"The corollary justified repeated U.S. intervention and a regional-police role.","Which answer describes more U.S. intervention nearby?"),
q("r11","CS 14","Neutrality to War","Which pair most directly shifted the United States toward entering World War I?",["Hawaiian annexation and the Treaty of Paris","The League covenant and Kellogg-Briand Pact","Unrestricted submarine warfare and the Zimmermann Telegram","The Roosevelt Corollary and disarmament"],2,"German submarine attacks and the proposed alliance with Mexico threatened U.S. security.","Select the two developments from 1917."),
q("r12","CS 14","Zimmermann Telegram","Why did the Zimmermann Telegram influence U.S. public opinion?",["It promised a lasting peace","It ended attacks on shipping","It offered the United States German territory","It suggested a hostile alliance that could threaten U.S. territory"],3,"The German offer to Mexico created a direct perceived threat near the U.S. border.","Why would an alliance with Mexico feel immediate to Americans?"),
q("r13","CS 14","U.S. Entry","Which claim best explains why submarine warfare mattered to the United States?",["It endangered American lives, ships, and neutral trading rights","It protected every passenger ship","It guaranteed Mexican neutrality","It reduced tensions with Germany"],0,"Attacks without warning harmed Americans and challenged claimed neutral rights.","Look for the direct harm caused by submarine attacks."),
q("r14","CS 14","Mobilization","How did U.S. mobilization contribute to Allied victory?",["It ended industrial production","It added troops, naval strength, supplies, and economic resources","It forced Britain and France to leave the war","It prevented American forces from reaching Europe"],1,"American military and economic capacity reinforced exhausted Allied nations.","Choose the answer adding resources to the Allied war effort."),
q("r15","CS 14","World-Power Status","Why did World War I accelerate America's rise relative to Europe?",["The United States required total rebuilding","Europe emerged economically untouched","European states were devastated while U.S. economic and military influence grew","The United States lost access to global finance"],2,"War damage and rebuilding burdens weakened Europe relative to the United States.","Compare where the war was fought and which economies required rebuilding."),
q("r16","CS 14","Cause and Effect","Which chain best explains American emergence as a world power?",["Disarmament → isolation → territorial loss","Neutrality → League membership → European control","Treaty rejection → smaller economy → weaker navy","Expansion and naval growth → victory over Spain → decisive World War I contribution"],3,"Each step increased the reach, credibility, and capacity of U.S. power.","Find the chronological chain in which every step increases influence."),
q("r17","CS 15","Peace Aims","Wilson proposes open diplomacy, lower armaments, freer trade, and national self-determination. What goal links these ideas?",["Removing causes of future wars","Expanding secret alliances","Punishing Germany above all else","Ending international cooperation"],0,"The Fourteen Points attempted to create conditions for a stable peace.","Ask what common problem these reforms were meant to prevent."),
q("r18","CS 15","Self-Determination","A people living inside a collapsing empire seek to form their own nation. Which Wilsonian principle supports them?",["Imperialism","Self-determination","Big Stick diplomacy","Unrestricted warfare"],1,"Self-determination supports peoples participating in decisions about their political status.","Who should determine the group's government and national future?"),
q("r19","CS 15","Collective Security","Several nations promise to respond together if one member is attacked. This arrangement is—",["yellow journalism","annexation","collective security","isolationism"],2,"Collective security relies on a group response to aggression.","The nations are acting collectively rather than individually."),
q("r20","CS 15","Versailles","Which difference created tension between Wilson and Allied leaders at Versailles?",["Wilson demanded colonies while Allies demanded self-determination","Wilson opposed any peace organization","Allied leaders wanted no penalties for Germany","Wilson emphasized a principled peace while Allies also sought punishment and compensation"],3,"European Allies placed greater emphasis on security, reparations, and punishing Germany.","Compare Wilson's idealism with the wartime losses suffered by Britain and France."),
q("r21","CS 15","League of Nations","What was Wilson's strongest proposed mechanism for maintaining peace?",["A League of Nations based on collective security","Permanent U.S. occupation of Germany","An expanded Spanish empire","An end to diplomacy"],0,"Point XIV proposed an association of nations to safeguard independence and territory.","Which institution was the capstone of Wilson's plan?"),
q("r22","CS 15","Senate Powers","Why could President Wilson not commit the United States to the Versailles Treaty by himself?",["The House alone ratifies treaties","The Constitution requires Senate advice and consent","State governors control foreign policy","The Supreme Court negotiates treaties"],1,"Treaty ratification requires the constitutionally specified Senate vote.","Recall the Senate's unique foreign-policy power."),
q("r23","CS 15","League Opposition","A senator fears League obligations could require U.S. military action without Congress independently choosing war. What is the senator protecting?",["Spain's colonial empire","The president's annexation power","Congressional authority and national freedom of action","Germany's submarine policy"],2,"League opponents feared collective obligations might weaken Congress's war power and U.S. autonomy.","Which U.S. institution has the power to declare war?"),
q("r24","CS 15","Treaty Politics","How did Wilson's refusal to accept Lodge's reservations affect the treaty struggle?",["It created immediate unanimous approval","It placed the treaty above the Constitution","It persuaded irreconcilables to support the League","It reduced chances for a compromise capable of winning Senate approval"],3,"The clash between Wilson and reservationists helped prevent a ratifying coalition.","Compromise requires accepting some conditions from potential supporters."),
q("r25","CS 15","Policy Outcome","Which event most clearly marked the postwar move away from world peacekeeper status?",["The United States refused to join the League of Nations","The United States mobilized in 1917","The United States annexed Hawaii","The United States defeated Spain"],0,"Staying outside the League limited the formal U.S. role in collective security.","Choose the postwar decision about permanent international cooperation."),
q("r26","CS 15","Isolationism","Which policy is the best example of postwar isolationism?",["Annexing additional European territory","Avoiding binding military alliances while participating selectively in diplomacy","Ending every foreign commercial relationship","Maintaining troops in every League nation"],1,"Isolationism limited political and military entanglements but did not mean total withdrawal.","Look for limited commitments, not total separation."),
q("r27","CS 15","Arms Limitation","Why were naval arms-limitation agreements compatible with isolationist attitudes?",["They required permanent U.S. military intervention","They created a world government","They sought peace without binding the United States to automatic collective action","They transferred the U.S. Navy to the League"],2,"The agreements pursued stability through limited cooperation without full League membership.","Which answer combines a peace effort with preserved independence?"),
q("r28","CS 15","Kellogg-Briand Pact","What was the central weakness of the Kellogg-Briand Pact?",["It required too much military enforcement","It created secret alliances","It promoted unrestricted submarine warfare","It renounced war but lacked strong enforcement mechanisms"],3,"The pact stated an ideal but provided little practical means to punish violators.","A promise is weaker when no effective consequence enforces it."),
q("r29","CS 14–15","Continuity and Change","Which comparison best describes U.S. policy before and after World War I?",["The nation gained global power but became more reluctant to accept permanent commitments","The nation lost all overseas influence and joined every alliance","The nation remained equally uninvolved throughout","The nation abandoned trade and diplomacy entirely"],0,"U.S. capacity grew even as political support for binding commitments declined.","Combine increased power with postwar caution."),
q("r30","CS 14–15","Historical Tension","Which tension is central to Block 3?",["Industrial growth versus farm machinery","Using global power while avoiding foreign entanglements","States' rights versus Reconstruction","Urbanization versus settlement houses"],1,"The United States emerged powerful but debated how deeply it should participate abroad.","Compare the title ideas world power and isolationism."),
q("r31","CS 14–15","Synthesis","Which evidence best supports the claim that the United States was not completely isolated after World War I?",["It refused League membership","It rejected the Versailles Treaty","It participated in arms agreements and the Kellogg-Briand Pact","It returned Puerto Rico to Spain"],2,"The United States still used selective diplomacy despite avoiding League obligations.","Isolationism was limited involvement, not zero involvement."),
q("r32","CS 14–15","Big Picture","Which thesis best summarizes CS 14–15?",["American foreign policy moved steadily toward complete withdrawal after 1898","World War I ended American economic influence","The League made the United States responsible for every foreign war","Expansion and war made the United States a world power, but treaty conflict encouraged selective isolationism"],3,"The thesis captures both the rise to power and the postwar retreat from binding commitments.","A complete thesis must explain both content statements, not only one.")
];
})();
