const ASSIGNMENT_KEY='AS-B6-CS22-23-INTRO-2026';
const PERIOD_TAB_PREFIX='B6 Intro P';
const SAVES_SHEET='Assignment Saves';
const WORK_SHEET='Student Work';
const HEADERS=['Assignment','Course','Period','Name','Email','Status','First Start','Last Save','Submitted','Score','Total','Percent','Answer Count','Wrong Attempts','Active Seconds','Away Seconds','Tab Leaves','Sessions','Answers JSON','Mastered JSON','Telemetry JSON','Payload JSON'];

function setup(){const ss=SpreadsheetApp.getActive();ensure_(ss,SAVES_SHEET);ensure_(ss,WORK_SHEET)}
function doGet(e){if(String(e.parameter.action)!=='load')return jsonp_(e.parameter.callback,{ok:true});const email=norm_(e.parameter.email),key=String(e.parameter.assignmentKey||'');const sh=ensure_(SpreadsheetApp.getActive(),SAVES_SHEET),row=find_(sh,key,email);return jsonp_(e.parameter.callback,row?{found:true,payload:JSON.parse(sh.getRange(row,22).getValue()||'{}')}:{found:false})}
function doPost(e){try{const p=JSON.parse(e.parameter.payload||'{}');if(p.assignmentKey!==ASSIGNMENT_KEY)throw new Error('Wrong assignment key');const ss=SpreadsheetApp.getActive(),m=upsert_(ensure_(ss,SAVES_SHEET),p);upsert_(ensure_(ss,WORK_SHEET),m);upsert_(ensure_(ss,tabName_(PERIOD_TAB_PREFIX+m.student.period)),m);return json_({ok:true})}catch(err){return json_({ok:false,error:String(err)})}}
function ensure_(ss,name){let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);if(sh.getLastRow()===0)sh.appendRow(HEADERS);return sh}
function upsert_(sh,p){const email=norm_(p.student&&p.student.email),row=find_(sh,p.assignmentKey,email),old=row?JSON.parse(sh.getRange(row,22).getValue()||'{}'):null,m=merge_(old,p),s=m.state||{},u=m.student||{};const v=[m.assignmentKey,'American Studies',u.period||'',u.name||'',email,s.status||'in progress',s.firstStart||'',m.updatedAt||new Date().toISOString(),s.submittedAt||'',m.score||0,m.total||0,m.percent||0,m.answerCount||0,m.wrongAttempts||0,Math.round(s.activeSeconds||0),Math.round(s.awaySeconds||0),s.tabLeaves||0,s.sessions||1,JSON.stringify(m.answers||{}),JSON.stringify(m.mastered||{}),JSON.stringify({events:s.events||[],attempts:s.attempts||{},questionSeconds:s.questionSeconds||{}}),JSON.stringify(m)];if(row)sh.getRange(row,1,1,HEADERS.length).setValues([v]);else sh.appendRow(v);return m}
function merge_(a,b){if(!a)return b;const o=b;o.answers=Object.assign({},a.answers||{},b.answers||{});o.mastered=Object.assign({},a.mastered||{},b.mastered||{});o.state=Object.assign({},a.state||{},b.state||{});o.state.answers=o.answers;o.state.mastered=o.mastered;o.state.attempts=Object.assign({},(a.state||{}).attempts||{},(b.state||{}).attempts||{});o.state.questionSeconds=Object.assign({},(a.state||{}).questionSeconds||{},(b.state||{}).questionSeconds||{});o.state.events=[...((a.state||{}).events||[]),...((b.state||{}).events||[])].slice(-500);o.state.firstStart=(a.state||{}).firstStart||(b.state||{}).firstStart;o.state.wrongTotal=Math.max((a.state||{}).wrongTotal||0,(b.state||{}).wrongTotal||0,b.wrongAttempts||0);o.state.activeSeconds=Math.max((a.state||{}).activeSeconds||0,(b.state||{}).activeSeconds||0);o.state.awaySeconds=Math.max((a.state||{}).awaySeconds||0,(b.state||{}).awaySeconds||0);o.state.tabLeaves=Math.max((a.state||{}).tabLeaves||0,(b.state||{}).tabLeaves||0);o.answerCount=Object.keys(o.answers).length;o.score=Object.keys(o.mastered).filter(k=>o.mastered[k]).length;o.percent=Math.round(o.score/(o.total||1)*100);o.wrongAttempts=o.state.wrongTotal;return o}
function find_(sh,key,email){if(sh.getLastRow()<2)return 0;const v=sh.getRange(2,1,sh.getLastRow()-1,5).getValues();for(let i=v.length-1;i>=0;i--)if(String(v[i][0])===key&&norm_(v[i][4])===email)return i+2;return 0}
function norm_(v){return String(v||'').trim().toLowerCase()}
function tabName_(v){return String(v).replace(/[\\/?*\[\]:]/g,'-').slice(0,99)}
function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function jsonp_(cb,o){const safe=String(cb||'callback').replace(/[^\w$]/g,'');return ContentService.createTextOutput(safe+'('+JSON.stringify(o)+');').setMimeType(ContentService.MimeType.JAVASCRIPT)}
