(function(){
const SRC={atom:"https://www.trumanlibrary.gov/education/presidential-inquiries/decision-drop-atomic-bomb",contain:"https://history.state.gov/milestones/1945-1952/kennan",truman:"https://history.state.gov/milestones/1945-1952/truman-doctrine",marshall:"https://history.state.gov/milestones/1945-1952/marshall-plan",nato:"https://history.state.gov/milestones/1945-1952/nato",korea:"https://history.state.gov/milestones/1945-1952/korean-war-1"};
const mode=location.pathname.includes("vocabulary")?"vocabulary":location.pathname.includes("review")?"review":"intro";
const meta={intro:["AS-B6-CS22-23-INTRO-2026","Block 6 Intro — Nuclear Age and Containment","CS 22–23 • Atomic weapons, superpower rivalry, and U.S. containment of communism."],vocabulary:["AS-B6-CS22-23-VOCAB-2026","Block 6 Vocabulary — Nuclear Age and Containment","CS 22–23 • Twenty-eight essential Cold War foundation terms."],review:["AS-B6-CS22-23-REVIEW-2026","Block 6 Comprehensive Review — Nuclear Age and Containment","CS 22–23 • Thirty-two application, cause-and-effect, comparison, and synthesis questions."]}[mode];window.BLOCK_CONFIG={assignmentKey:meta[0],title:meta[1],description:meta[2],practice:"Explain how atomic weapons changed war and power, why containment developed, and how economic aid, alliances, and wars applied that policy."};
const C=[
["CS 22","Atomic bomb","Weapon using nuclear fission to release unprecedented destructive energy","One aircraft delivers a weapon capable of destroying much of a city",SRC.atom],
["CS 22","Hiroshima","Japanese city struck by the first atomic bomb used in war","A uranium bomb is dropped on August 6, 1945",SRC.atom],
["CS 22","Nagasaki","Japanese city struck by the second wartime atomic bomb","A plutonium bomb is dropped on August 9, 1945",SRC.atom],
["CS 22","Nuclear age","Era in which nuclear weapons shape warfare, diplomacy, and public fear","International politics changes because nations can threaten mass destruction",SRC.atom],
["CS 22","Mass destruction","Destructive capacity capable of killing enormous populations and devastating cities","A single weapon produces blast, fire, and radiation across a wide area",SRC.atom],
["CS 22","Superpower","Nation possessing extraordinary global military, economic, and political influence","The United States gains heightened status from economic strength and atomic capability",SRC.atom],
["CS 22","Balance of power","Distribution of power among states that shapes security and restraint","One nation's monopoly gives way when a rival acquires a comparable weapon",SRC.atom],
["CS 22","Soviet atomic bomb","1949 development ending the U.S. nuclear monopoly","Successful Soviet testing creates a second nuclear-armed superpower",SRC.atom],
["CS 22","Nuclear arms race","Competition to build larger and more advanced nuclear arsenals","The United States and Soviet Union repeatedly expand weapons stockpiles",SRC.atom],
["CS 22","Deterrence","Preventing attack by threatening unacceptable retaliation","A rival hesitates because striking first could bring devastating response",SRC.atom],
["CS 22","Radiation","Energy released by nuclear reactions that can cause lasting health damage","Survivors face effects beyond blast and fire",SRC.atom],
["CS 22","Conventional warfare","Conflict fought with nonnuclear weapons","Armies use artillery, aircraft, and rifles without atomic weapons",SRC.atom],
["CS 22","Hastening surrender","Argument that atomic attacks accelerated Japan's decision to end World War II","Leaders claim the new weapon shortened the Pacific war",SRC.atom],
["CS 22","Nuclear fear","Public anxiety about annihilation in a possible superpower war","Families worry that a future conflict could destroy entire cities",SRC.atom],
["CS 23","Containment","U.S. policy designed to prevent communism from spreading to additional countries","Officials resist expansion rather than trying immediately to eliminate communism everywhere",SRC.contain],
["CS 23","Soviet expansion","Extension of Soviet influence over Eastern Europe after World War II","Communist governments aligned with Moscow take power across the region",SRC.contain],
["CS 23","Communist China","1949 victory of Mao's communist forces in China","The world's most populous nation becomes communist",SRC.contain],
["CS 23","Truman Doctrine","U.S. pledge to support peoples resisting communist pressure","American aid assists Greece and Turkey",SRC.truman],
["CS 23","Marshall Plan","Large U.S. economic-aid program for European recovery","Rebuilding economies is used to reduce communist appeal",SRC.marshall],
["CS 23","NATO","Collective-defense alliance joining the United States, Canada, and Western Europe","Members agree an attack on one will be treated as an attack on all",SRC.nato],
["CS 23","Collective defense","Security principle in which allies promise mutual response to attack","Several countries deter aggression by standing together",SRC.nato],
["CS 23","Economic containment","Using aid and recovery to reduce conditions favorable to communism","Food, equipment, and investment strengthen unstable democracies",SRC.marshall],
["CS 23","Military containment","Using armed alliances or force to block communist expansion","Troops and defense commitments oppose an invasion",SRC.nato],
["CS 23","Korean War","Conflict in which containment led the United States to defend South Korea","U.N. and U.S. forces resist North Korea's invasion",SRC.korea],
["CS 23","Vietnam War","Later Asian conflict in which the United States tried to prevent communist expansion","American involvement grows to support South Vietnam",SRC.contain],
["CS 23","Europe","Initial central region for U.S. containment after World War II","Marshall aid and NATO focus heavily on this continent",SRC.marshall],
["CS 23","Asia","Region where communist victory in China and wars in Korea and Vietnam expanded containment","U.S. strategy extends beyond Europe",SRC.korea],
["CS 23","Latin America","Region where U.S. officials later applied containment against perceived communist influence","Cold War policy expands into the Western Hemisphere",SRC.contain]
];
function opts(n,f){return[1,7,13].map(k=>C[(n+k)%C.length][f])}function make(kind){return C.map((c,n)=>{const answer=n%4,choices=opts(n,1);choices.splice(answer,0,c[1]);return{id:`${kind[0]}${String(n+1).padStart(2,"0")}`,cs:c[0],topic:c[1],prompt:kind==="vocabulary"?`Which term matches this definition: ${c[2]}?`:kind==="intro"?`According to the source, which development is described? ${c[2]}.`:`${c[3]}. Which concept best applies?`,choices,answer,source:kind==="review"?"":c[4],where:kind==="review"?"":"Locate the described weapon, policy, alliance, region, or consequence.",explanation:`This is ${c[1]}: ${c[2].charAt(0).toLowerCase()+c[2].slice(1)}.`,hint:`Connect the clue to ${c[1]} and its role in the early Cold War.`}})}
const E=[["CS 22","Cause and Effect","Which chain is most accurate?","Soviet atomic test ends U.S. monopoly → arms race → heightened nuclear fear",["Containment → Prohibition → Hiroshima","Marshall Plan → Japanese surrender → Red Scare","NATO → end of nuclear weapons → isolation"],"Soviet acquisition transformed a monopoly into a dangerous superpower competition."],["CS 23","Policy Comparison","Which pairing correctly distinguishes containment tools?","Marshall Plan—economic aid; NATO—collective military defense",["Truman Doctrine—Prohibition; NATO—trade only","Marshall Plan—atomic attack; NATO—deportation","Korean War—economic aid only; Marshall Plan—military alliance"],"Containment combined economic and military instruments."],["CS 22–23","Connection","How did nuclear weapons affect containment?","They made direct superpower war more dangerous, encouraging indirect competition and alliances",["They eliminated rivalry","They ended the need for diplomacy","They caused immediate Soviet surrender"],"Nuclear risk shaped how the rivals confronted one another."],["CS 22–23","Synthesis","Which thesis best summarizes Block 6?","Nuclear weapons created superpower danger while containment used aid, alliances, and limited wars to resist communist expansion",["The United States returned to complete isolation","Atomic weapons ended all conventional war","Containment operated only in Europe"],"The block connects nuclear transformation with a global strategy."]];function extras(){return E.map((e,j)=>{const n=28+j,a=n%4,ch=e[4].slice();ch.splice(a,0,e[3]);return{id:`r${n+1}`,cs:e[0],topic:e[1],prompt:e[2],choices:ch,answer:a,source:"",where:"",explanation:e[5],hint:"Choose the answer that accurately connects causes, tools, regions, and consequences."}})}
window.BLOCK_QUESTIONS=mode==="intro"?make("intro"):mode==="vocabulary"?make("vocabulary"):[...make("review"),...extras()];
})();
