const CONFIG={assignmentId:'founding-documents-phase-iii',assignmentTitle:'Founding Documents - Phase III',appsScriptUrl:'PASTE_YOUR_APPS_SCRIPT_WEB_APP_URL_HERE'};
const SOURCES={northwest:['Northwest Ordinance','https://www.archives.gov/milestone-documents/northwest-ordinance'],constitution:['Constitution','https://www.archives.gov/founding-docs/constitution-transcript'],checks:['Checks and balances','https://constitution.congress.gov/browse/essay/intro.6-2-2/ALDE_00000031/'],ratification:['Ratification debate','https://www.archives.gov/founding-docs/more-perfect-union'],federalism:['Federalism','https://constitution.congress.gov/browse/essay/intro.7-3/ALDE_00000032/'],billrights:['Bill of Rights','https://www.archives.gov/founding-docs/bill-of-rights-transcript'],articles:['Articles of Confederation','https://www.archives.gov/milestone-documents/articles-of-confederation'],founding:['Founding Documents','https://www.archives.gov/founding-docs']};
const QUESTIONS=[
 ['Explain how the Northwest Ordinance set precedents for civil liberties later included in the Bill of Rights.',['northwest','billrights'],'Identify at least two protections and connect them across the documents.'],
 ['Describe how the Constitution’s system of checks and balances limits the power of government. Provide one historical example.',['constitution','checks'],'Explain both the constitutional check and how your example demonstrates it.'],
 ['Compare Federalist and Anti-Federalist arguments about national taxation. Which do you think was more valid, and why?',['ratification','articles'],'Represent both sides fairly before defending your judgment.'],
 ['Analyze how the prohibition of slavery in the Northwest Ordinance connected to later debates leading up to the Civil War.',['northwest'],'Use Article VI and explain how territorial expansion kept the slavery question alive.'],
 ['How does the principle of federalism balance power between national and state governments? Provide an example.',['federalism','constitution'],'Define the division of authority, then illustrate it.'],
 ['Evaluate how the Bill of Rights continues to protect Americans today. Use a modern example.',['billrights'],'Identify a specific amendment and apply it to a credible modern situation.'],
 ['How did the Constitution ensure that power came from the consent of the governed?',['constitution'],'Use the Preamble and at least one representative or electoral feature.'],
 ['Explain how the Northwest Ordinance’s emphasis on education reflected the role of citizens in a democracy.',['northwest'],'Connect knowledge and schooling to responsible self-government.'],
 ['Compare the weaknesses of the Articles of Confederation with the solutions provided in the Constitution.',['articles','constitution'],'Match at least two weaknesses with the constitutional powers or structures that addressed them.'],
 ['In your opinion, which Founding Document had the greatest impact on shaping American democracy? Defend your answer with evidence.',['founding'],'State a clear claim, cite document evidence, and explain why its impact was greatest.']
];
const $=id=>document.getElementById(id),storageKey=()=>`${CONFIG.assignmentId}:${($('email').value||'anonymous').trim().toLowerCase()}`;
function render(){QUESTIONS.forEach((q,i)=>{const links=q[1].map(k=>`<a class="source-link" href="${SOURCES[k][1]}" target="_blank" rel="noopener">${SOURCES[k][0]} ↗</a>`).join('');const card=document.createElement('article');card.className='question-card';card.innerHTML=`<div class="question-top"><p class="question-text"><span class="number">${i+1}</span>${q[0]}</p><div class="sources">${links}</div></div><label for="q${i+1}">Your extended response<textarea id="q${i+1}" aria-label="Response to question ${i+1}"></textarea></label><p class="hint"><strong>Response target:</strong> ${q[2]}</p>`;$('questions').appendChild(card);});}
function collect(){return{assignmentId:CONFIG.assignmentId,assignmentTitle:CONFIG.assignmentTitle,studentName:$('studentName').value.trim(),period:$('period').value,email:$('email').value.trim().toLowerCase(),answers:QUESTIONS.map((_,i)=>$(`q${i+1}`).value.trim()),savedAt:new Date().toISOString()};}
function fill(d){if(!d)return;$('studentName').value=d.studentName||'';$('period').value=d.period||'';$('email').value=d.email||'';(d.answers||[]).forEach((a,i)=>{if($(`q${i+1}`))$(`q${i+1}`).value=a;});update();}
function status(m,e=false){$('saveStatus').textContent=m;$('saveStatus').style.color=e?'#a32026':''}function configured(){return /^https:\/\/script\.google\.com\/.+\/exec/.test(CONFIG.appsScriptUrl)}
function save(show=true){const d=collect();localStorage.setItem(storageKey(),JSON.stringify(d));if(show)status('Saved on this device.');return d}async function post(action,d){if(!configured())return false;await fetch(CONFIG.appsScriptUrl,{method:'POST',mode:'no-cors',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({action,payload:JSON.stringify(d)})});return true}
function cloudRetrieve(){return new Promise((resolve,reject)=>{if(!configured())return reject(new Error('Cloud saving is not configured.'));const cb=`worksheetCb${Date.now()}`,s=document.createElement('script'),t=setTimeout(()=>{clean();reject(new Error('Cloud retrieval timed out.'))},10000);function clean(){clearTimeout(t);delete window[cb];s.remove()}window[cb]=d=>{clean();d&&d.found?resolve(d.payload):reject(new Error('No cloud draft found.'))};s.onerror=()=>{clean();reject(new Error('Could not reach cloud storage.'))};s.src=`${CONFIG.appsScriptUrl}?action=retrieve&assignmentId=${encodeURIComponent(CONFIG.assignmentId)}&email=${encodeURIComponent($('email').value.trim().toLowerCase())}&callback=${cb}`;document.body.appendChild(s)})}
function update(){const n=QUESTIONS.filter((_,i)=>$(`q${i+1}`).value.trim()).length;$('progressText').textContent=`${n} of ${QUESTIONS.length} answered`;$('progressBar').value=n}
function validate(){document.querySelectorAll('.field-error').forEach(e=>e.classList.remove('field-error'));const m=[];['studentName','period','email'].forEach(id=>{if(!$(`${id}`).value.trim())m.push($(`${id}`))});QUESTIONS.forEach((_,i)=>{if($(`q${i+1}`).value.trim().split(/\s+/).length<20)m.push($(`q${i+1}`))});if(m.length){m.forEach(e=>e.classList.add('field-error'));m[0].scrollIntoView({behavior:'smooth',block:'center'});return false}return true}
render();document.addEventListener('input',()=>{update();clearTimeout(window.autoSaveTimer);window.autoSaveTimer=setTimeout(()=>save(false),600)});$('saveBtn').onclick=async()=>{const d=save();try{if(await post('save',d))status('Saved on this device and to your cloud draft.')}catch(e){status('Saved on this device; cloud save was unavailable.',true)}};$('retrieveBtn').onclick=async()=>{if(!$('email').value.trim())return status('Enter your school email first.',true);const d=localStorage.getItem(storageKey());if(d){fill(JSON.parse(d));return status('Previous work restored from this device.')}try{fill(await cloudRetrieve());status('Previous cloud draft restored.')}catch(e){status(e.message,true)}};$('assignmentForm').onsubmit=async e=>{e.preventDefault();if(!validate()){$('submitStatus').textContent='Please complete every highlighted response with at least 20 words.';return}const d=save(false);$('submitBtn').disabled=true;$('submitStatus').textContent='Submitting…';try{if(configured()){await post('submit',d);$('submitStatus').textContent='Submitted successfully. Your teacher now has your responses.'}else $('submitStatus').textContent='Your work is complete and saved on this device. Your teacher must configure the submission URL before it can be sent.'}catch(err){$('submitStatus').textContent='Submission could not be sent. Your work remains saved; try again.';$('submitBtn').disabled=false}};update();
