const APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbxOHGJjzKdU-p8EZQeylAZg18k9V-jF7uTV_eZI-YeAdP_W-U53umVb73_aNVoJv83ImA/exec";
const ASSIGNMENT_KEY = "AS-B2-CS6-7-INTRO-2026";
const questions = window.BLOCK_QUESTIONS;
function q(id,cs,prompt,choices,answer,source,where,explanation){return{id,cs,prompt,choices,answer,source,where,explanation,hint:where}}

const state={answers:{},mastered:{},attempts:{},wrongTotal:0,firstStart:new Date().toISOString(),sessions:1,activeSeconds:0,awaySeconds:0,tabLeaves:0,events:[],questionSeconds:{},currentQuestion:null,lastTick:Date.now(),status:"in progress"};
const $=id=>document.getElementById(id); const storageKey=()=>`${ASSIGNMENT_KEY}|${$('email').value.trim().toLowerCase()}`;

function render(){
 $('totalCount').textContent=questions.length;
 $('questions').innerHTML=questions.map((x,n)=>`<article class="question" id="card-${x.id}"><div class="qtop"><span class="qnum">Question ${n+1}</span><span class="cs">${x.cs}</span></div><div class="prompt">${x.prompt}</div><div class="research"><a class="source-link" href="${x.source}" target="_blank" rel="noopener">Open source</a><p class="where"><strong>Where to look:</strong> ${x.where}</p></div><div class="choices">${x.choices.map((c,i)=>`<label class="choice"><input type="radio" name="${x.id}" value="${i}"> <span>${c}</span></label>`).join('')}</div><div class="check-row"><button data-check="${x.id}">Check answer</button></div><div class="feedback" id="fb-${x.id}" role="status"></div></article>`).join('');
 document.querySelectorAll('[data-check]').forEach(b=>b.addEventListener('click',()=>check(b.dataset.check)));
 document.querySelectorAll('.question').forEach(card=>card.addEventListener('focusin',()=>state.currentQuestion=card.id.slice(5)));
 restoreLocal(); update();
}
function check(id){
 const x=questions.find(v=>v.id===id),picked=document.querySelector(`input[name="${id}"]:checked`),fb=$(`fb-${id}`);
 if(!picked){fb.className='feedback hint';fb.textContent='Choose an answer first.';return}
 const value=Number(picked.value); state.answers[id]=value; state.attempts[id]=(state.attempts[id]||0)+1;
 if(value===x.answer){state.mastered[id]=true;fb.className='feedback good';fb.innerHTML=`<strong>Correct.</strong> ${x.explanation}`;$(`card-${id}`).classList.add('mastered');$(`card-${id}`).querySelectorAll('input,button').forEach(el=>el.disabled=true)}
 else{state.wrongTotal++;fb.className='feedback bad';fb.innerHTML=`<strong>Not yet.</strong> Hint: ${x.hint}`}
 saveLocal();update();queueCloudSave();
}
function update(){const m=Object.keys(state.mastered).filter(k=>state.mastered[k]).length,a=Object.values(state.attempts).reduce((s,v)=>s+v,0);$('masteredCount').textContent=m;$('attemptCount').textContent=a;$('barFill').style.width=`${m/questions.length*100}%`;$('submitBtn').disabled=m!==questions.length}
function student(){return{name:$('studentName').value.trim(),period:$('period').value,email:$('email').value.trim().toLowerCase()}}
function payload(){tick();return{assignmentKey:ASSIGNMENT_KEY,student:student(),state:state,answers:state.answers,mastered:state.mastered,score:Object.keys(state.mastered).length,total:questions.length,percent:Math.round(Object.keys(state.mastered).length/questions.length*100),answerCount:Object.keys(state.answers).length,wrongAttempts:state.wrongTotal,updatedAt:new Date().toISOString()}}
function saveLocal(){if(!$('email').value.trim())return;localStorage.setItem(storageKey(),JSON.stringify(payload()))}
function restoreLocal(){const raw=localStorage.getItem(storageKey());if(!raw)return;try{mergeDraft(JSON.parse(raw));$('saveStatus').textContent='Local draft restored.'}catch{}}
function mergeDraft(d){if(!d)return;const s=d.state||d;for(const [k,v] of Object.entries(s.answers||d.answers||{}))if(state.answers[k]===undefined||state.answers[k]==='')state.answers[k]=v;Object.assign(state.mastered,s.mastered||d.mastered||{});for(const[k,v]of Object.entries(s.attempts||{}))state.attempts[k]=Math.max(state.attempts[k]||0,v||0);state.wrongTotal=Math.max(state.wrongTotal||0,s.wrongTotal||d.wrongAttempts||0);state.firstStart=s.firstStart||state.firstStart;applyState()}
function applyState(){for(const x of questions){if(state.answers[x.id]!==undefined){const el=document.querySelector(`input[name="${x.id}"][value="${state.answers[x.id]}"]`);if(el)el.checked=true}if(state.mastered[x.id]){const card=$(`card-${x.id}`),fb=$(`fb-${x.id}`);card.classList.add('mastered');card.querySelectorAll('input,button').forEach(el=>el.disabled=true);fb.className='feedback good';fb.innerHTML=`<strong>Correct.</strong> ${x.explanation}`}}update()}
let saveTimer;function queueCloudSave(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>cloudSave(false),900)}
async function cloudSave(manual){if(!validStudent(false)||APPS_SCRIPT_URL.startsWith('PASTE_')){if(manual)$('saveStatus').textContent=APPS_SCRIPT_URL.startsWith('PASTE_')?'Saved on this device. Add the Apps Script URL for cloud saving.':'Enter name, period, and school email.';return}saveLocal();try{await fetch(APPS_SCRIPT_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({action:'save',payload:JSON.stringify(payload())})});$('saveStatus').textContent='Saved on this device and sent to your teacher draft.'}catch{$('saveStatus').textContent='Saved on this device. Cloud save could not be confirmed.'}}
function loadCloud(){if(!validStudent(true)||APPS_SCRIPT_URL.startsWith('PASTE_'))return;const cb=`load_${Date.now()}`;window[cb]=r=>{try{if(r&&r.found)mergeDraft(r.payload);saveLocal();$('saveStatus').textContent=r&&r.found?'Previous work merged safely.':'No cloud draft was found.'}finally{delete window[cb];script.remove()}};const script=document.createElement('script');script.src=`${APPS_SCRIPT_URL}?action=load&assignmentKey=${encodeURIComponent(ASSIGNMENT_KEY)}&email=${encodeURIComponent(student().email)}&callback=${cb}`;script.onerror=()=>{$('saveStatus').textContent='Could not load the cloud draft.';delete window[cb];script.remove()};document.body.appendChild(script)}
function validStudent(show=true){const s=student(),ok=s.name&&s.period&&/^\S+@\S+\.\S+$/.test(s.email);if(!ok&&show)$('saveStatus').textContent='Enter full name, period, and a valid school email first.';return ok}
function tick(){const now=Date.now(),seconds=Math.max(0,Math.round((now-state.lastTick)/1000));if(document.hidden)state.awaySeconds+=seconds;else state.activeSeconds+=seconds;if(state.currentQuestion)state.questionSeconds[state.currentQuestion]=(state.questionSeconds[state.currentQuestion]||0)+seconds;state.lastTick=now}
setInterval(()=>{tick();saveLocal()},15000);document.addEventListener('visibilitychange',()=>{tick();state.tabLeaves+=document.hidden?1:0;state.events.push({type:document.hidden?'leave':'return',at:new Date().toISOString()})});document.addEventListener('copy',e=>{const card=e.target.closest('.question');state.events.push({type:'copy',question:card?card.id.slice(5):'',at:new Date().toISOString()})});document.addEventListener('paste',e=>{const card=e.target.closest('.question');state.events.push({type:'paste',question:card?card.id.slice(5):'',at:new Date().toISOString()})});
$('studentName').addEventListener('change',restoreLocal);$('email').addEventListener('change',restoreLocal);$('period').addEventListener('change',saveLocal);$('saveBtn').addEventListener('click',()=>cloudSave(true));$('loadBtn').addEventListener('click',loadCloud);$('submitBtn').addEventListener('click',async()=>{if(!validStudent(true))return;state.status='submitted';state.submittedAt=new Date().toISOString();await cloudSave(true);$('submitStatus').textContent='Submitted successfully at 100% mastery.';$('submitBtn').disabled=true});render();
