const ASSIGNMENT_KEY = 'AS-B2-CS6-7-INTRO-2026';
const SAVES_SHEET = 'Assignment Saves';
const WORK_SHEET = 'Student Work';
const HEADERS = ['Assignment','Course','Period','Name','Email','Status','First Start','Last Save','Submitted','Score','Total','Percent','Answer Count','Wrong Attempts','Active Seconds','Away Seconds','Tab Leaves','Sessions','Answers JSON','Mastered JSON','Telemetry JSON','Payload JSON'];

function setup(){const ss=SpreadsheetApp.getActive();ensure_(ss,SAVES_SHEET);ensure_(ss,WORK_SHEET)}
function doGet(e){if(String(e.parameter.action)!=='load')return jsonp_(e.parameter.callback,{ok:true});const email=norm_(e.parameter.email),key=String(e.parameter.assignmentKey||'');const sh=ensure_(SpreadsheetApp.getActive(),SAVES_SHEET),row=find_(sh,key,email);return jsonp_(e.parameter.callback,row?{found:true,payload:JSON.parse(sh.getRange(row,22).getValue()||'{}')}:{found:false})}
function doPost(e){try{const p=JSON.parse(e.parameter.payload||'{}');if(p.assignmentKey!==ASSIGNMENT_KEY)throw new Error('Wrong assignment key');const ss=SpreadsheetApp.getActive(),merged=upsert_(ensure_(ss,SAVES_SHEET),p);upsert_(ensure_(ss,WORK_SHEET),merged);upsert_(ensure_(ss,tabName_('B2 Intro P'+merged.student.period)),merged);return json_({ok:true})}catch(err){return json_({ok:false,error:String(err)})}}
function ensure_(ss,name){let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);if(sh.getLastRow()===0)sh.appendRow(HEADERS);return sh}
function upsert_(sh,p){const email=norm_(p.student&&p.student.email),row=find_(sh,p.assignmentKey,email),old=row?JSON.parse(sh.getRange(row,22).getValue()||'{}'):null,m=merge_(old,p),s=m.state||{},student=m.student||{};const values=[m.assignmentKey,'American Studies',student.period||'',student.name||'',email,s.status||'in progress',s.firstStart||'',m.updatedAt||new Date().toISOString(),s.submittedAt||'',m.score||0,m.total||0,m.percent||0,m.answerCount||0,m.wrongAttempts||0,s.activeSeconds||0,s.awaySeconds||0,s.tabLeaves||0,s.sessions||1,JSON.stringify(m.answers||{}),JSON.stringify(m.mastered||{}),JSON.stringify(s.events||[]),JSON.stringify(m)];if(row)sh.getRange(row,1,1,HEADERS.length).setValues([values]);else sh.appendRow(values);return m}
function merge_(a,b){if(!a)return b;const out=b;out.answers=Object.assign({},a.answers||{},b.answers||{});for(const k in a.answers||{})if((b.answers||{})[k]===''||(b.answers||{})[k]==null)out.answers[k]=a.answers[k];out.mastered=Object.assign({},a.mastered||{},b.mastered||{});out.state=Object.assign({},a.state||{},b.state||{});out.state.answers=out.answers;out.state.mastered=out.mastered;out.state.firstStart=(a.state||{}).firstStart||(b.state||{}).firstStart;out.state.wrongTotal=Math.max((a.state||{}).wrongTotal||0,(b.state||{}).wrongTotal||0);out.answerCount=Object.keys(out.answers).filter(k=>out.answers[k]!==''&&out.answers[k]!=null).length;out.score=Object.keys(out.mastered).filter(k=>out.mastered[k]).length;out.percent=Math.round(out.score/(out.total||1)*100);return out}
function find_(sh,key,email){if(sh.getLastRow()<2)return 0;const v=sh.getRange(2,1,sh.getLastRow()-1,5).getValues();for(let i=v.length-1;i>=0;i--)if(String(v[i][0])===key&&norm_(v[i][4])===email)return i+2;return 0}
function norm_(v){return String(v||'').trim().toLowerCase()}
function tabName_(v){return String(v).replace(/[\\/?*\[\]:]/g,'-').slice(0,99)}
function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function jsonp_(cb,o){const safe=String(cb||'callback').replace(/[^\w$]/g,'');return ContentService.createTextOutput(safe+'('+JSON.stringify(o)+');').setMimeType(ContentService.MimeType.JAVASCRIPT)}
