(function(){
const CON="https://www.archives.gov/founding-docs/constitution-transcript";
const HIST="https://www.archives.gov/founding-docs/more-perfect-union";
const LOC="https://www.loc.gov/exhibits/creating-the-united-states/convention-and-ratification.html";
const BOR="https://www.archives.gov/founding-docs/bill-of-rights-transcript";
const q=(id,cs,prompt,choices,answer,source,where,explanation)=>({id,cs,prompt,choices,answer,source,where,explanation,hint:where});
window.BLOCK_QUESTIONS=[
q("i01","CS 6","Why was the Constitution written to replace the Articles of Confederation?",["The national government needed enough power to address national problems","The states wanted to restore British rule","The nation wanted to eliminate state governments","The courts demanded a hereditary ruler"],0,HIST,"Read the opening sections about weaknesses under the Articles and the need for a stronger union.","The Constitution strengthened the national government so it could act on problems the Confederation could not solve."),
q("i02","CS 6","Which opening words identify the source of the Constitution's authority?",["The several States","We the People","The national army","The Supreme Court"],1,CON,"Read the first three words of the Preamble.","“We the People” places ultimate authority in the people."),
q("i03","CS 6","Which constitutional principle divides national power among legislative, executive, and judicial branches?",["Federalism","Popular sovereignty","Separation of powers","Judicial restraint"],2,CON,"Scan Articles I, II, and III and note that each vests power in a different institution.","Separation of powers assigns governmental functions to three branches."),
q("i04","CS 6","Which article establishes the legislative branch?",["Article IV","Article III","Article II","Article I"],3,CON,"Go to Article I and read its opening sentence.","Article I vests legislative power in Congress."),
q("i05","CS 6","What is Congress empowered to do that the Confederation government could not do effectively?",["Levy taxes","Choose state governors","Abolish elections","Control all local schools"],0,CON,"In Article I, Section 8, read the first listed congressional power.","The Constitution gives Congress power to lay and collect taxes."),
q("i06","CS 6","Which branch carries out or enforces federal laws?",["Legislative","Executive","Judicial","State"],1,CON,"Read the opening of Article II and identify the office receiving executive power.","The executive branch, led by the president, enforces federal law."),
q("i07","CS 6","Which branch interprets federal law when deciding cases?",["Executive","Legislative","Judicial","Military"],2,CON,"Read Article III and look for the judicial power of the United States.","The judicial branch interprets laws through cases and controversies."),
q("i08","CS 6","Federalism divides governmental power between which two levels?",["Courts and juries","House and Senate","Voters and candidates","National and state governments"],3,CON,"Read Article I's national powers and then Article IV's relationships involving states.","Federalism divides authority between the national government and the states."),
q("i09","CS 6","How does the Constitution create a limited government?",["It grants defined powers and places government under a written supreme law","It permits officials to ignore laws during disagreements","It gives every power to one branch","It ends the people's role after elections"],0,CON,"Look at the specific grants of power in Articles I–III and the supremacy rule in Article VI.","A written Constitution defines and limits governmental authority."),
q("i10","CS 6","How do regular elections help define the relationship between people and government?",["They allow courts to write laws","They allow people to choose representatives","They permit presidents to serve for life","They replace the Constitution"],1,CON,"Read Article I, Section 2 and the selection of members of the House.","Elections give the people a continuing role in selecting representatives."),
q("i11","CS 6","Which phrase best describes checks and balances?",["States may leave the Union whenever they disagree","The majority may eliminate minority rights","Each branch can restrain certain actions of the others","Congress controls all three branches"],2,CON,"Compare Congress's lawmaking power, the president's veto, and the Senate's advice-and-consent powers.","Checks and balances let branches limit one another so power is not concentrated."),
q("i12","CS 6","Which action is an example of amending the Constitution?",["A governor issues an order","A court postpones a trial","Congress passes an ordinary bill","The nation formally adds or changes constitutional language through Article V"],3,CON,"Go to Article V and identify the formal change process.","An amendment formally changes or adds to the Constitution."),
q("i13","CS 6","Why is the Constitution called the supreme law of the land?",["Article VI places it above conflicting state law","It allows the president to cancel elections","It makes every federal policy permanent","It prevents courts from interpreting laws"],0,CON,"Read Article VI and find the phrase “supreme Law of the Land.”","Article VI makes the Constitution and valid federal law supreme over conflicting state law."),
q("i14","CS 6","Which constitutional power most directly addressed the inability to maintain a national defense?",["Power to establish schools","Power to raise and support armies","Power to appoint mayors","Power to regulate state constitutions"],1,CON,"In Article I, Section 8, scan for powers involving armies and a navy.","Congress received power to raise and support armies and provide a navy."),
q("i15","CS 6","Which power allows Congress to manage trade among the states?",["Treaty power","Veto power","Commerce power","Pardon power"],2,CON,"In Article I, Section 8, find the clause about commerce among the several states.","The Commerce Clause authorizes Congress to regulate interstate commerce."),
q("i16","CS 6","What does ratification mean?",["Interpreting a court ruling","Rejecting a proposed document","Writing a newspaper editorial","Formally approving a proposed constitution or amendment"],3,HIST,"Find the sections describing state conventions approving the proposed Constitution.","Ratification is formal approval."),
q("i17","CS 7","Who were the Federalists during the ratification debate?",["Supporters of ratifying the Constitution","Supporters of returning to monarchy","Opponents of any national union","Delegates who wanted no written laws"],0,LOC,"Find “The Federalist Papers” and read why the essays were written.","Federalists supported ratification of the proposed Constitution."),
q("i18","CS 7","What was the main purpose of the Federalist Papers?",["To demand independence from Britain","To persuade readers to ratify the Constitution","To abolish state government","To replace the Bill of Rights"],1,LOC,"Read the caption explaining why Madison, Hamilton, and Jay wrote the essays.","The Federalist Papers defended the Constitution and encouraged ratification."),
q("i19","CS 7","Which three writers produced the Federalist Papers?",["Washington, Franklin, and Adams","Jefferson, Henry, and Lee","Hamilton, Madison, and Jay","Locke, Hobbes, and Montesquieu"],2,LOC,"Find the names listed in the Federalist Papers section.","Alexander Hamilton, James Madison, and John Jay wrote the essays."),
q("i20","CS 7","Which position would a Federalist most likely support?",["A national government unable to collect revenue","No national defense","Complete supremacy of each state","A stronger national government with taxation, defense, and checks and balances"],3,HIST,"Read the ratification discussion and identify arguments favoring the new framework.","Federalists believed an effective Union required greater national power with internal safeguards."),
q("i21","CS 7","Which concern would an Anti-Federalist most likely raise?",["A powerful national government could threaten individual liberty","Congress would be too weak to tax","The president would have no executive power","The Constitution protected too many listed rights"],0,HIST,"Find the Bill of Rights section and read the Anti-Federalist criticism of the proposed Constitution.","Anti-Federalists feared centralized power and the absence of explicit protections for liberty."),
q("i22","CS 7","Why did Anti-Federalists object to a standing army?",["They wanted Britain to provide defense","They feared it could be used against citizens","They believed states had no militias","They opposed every form of defense"],1,HIST,"Read the Anti-Federalist objections concerning concentrated power and possible tyranny.","Anti-Federalists feared a permanent national army could become an instrument of oppression."),
q("i23","CS 7","What compromise helped secure ratification in closely divided states?",["Eliminating the presidency","Ending national taxation","Promising to add amendments protecting individual rights","Allowing each state to ignore the Constitution"],2,HIST,"Read the paragraphs immediately before the heading “The Bill of Rights.”","Promises to consider protective amendments helped win ratification."),
q("i24","CS 7","What is the Bill of Rights?",["The list of Declaration grievances","The original seven articles","A collection of Federalist essays","The first ten amendments to the Constitution"],3,BOR,"Read the introductory note above the amendments.","The first ten amendments are known as the Bill of Rights."),
q("i25","CS 7","How did the Anti-Federalists influence the final constitutional system?",["Their demand for explicit protections helped produce the Bill of Rights","They replaced the Constitution with the Articles","They abolished the national courts","They ended the amendment process"],0,HIST,"Read how Anti-Federalist arguments affected the debate and Madison's later actions.","Anti-Federalist pressure helped bring about amendments protecting liberties."),
q("i26","CS 7","Which freedom is explicitly protected in the First Amendment?",["Freedom from every tax","Freedom of speech","A guaranteed government job","The right to inherit office"],1,BOR,"Read Amendment I and identify its five protected freedoms.","The First Amendment protects speech along with religion, press, assembly, and petition."),
q("i27","CS 7","Which protection responds directly to fear of arbitrary government searches?",["The Second Amendment","The Tenth Amendment","The Fourth Amendment","Article II"],2,BOR,"Read Amendment IV and locate “unreasonable searches and seizures.”","The Fourth Amendment protects against unreasonable searches and seizures."),
q("i28","CS 6–7","Which statement best connects the Constitution, ratification debate, and Bill of Rights?",["The Constitution eliminated debate by listing every liberty at first","Anti-Federalists supported unlimited central power","Federalists rejected constitutional government","The Constitution strengthened government, and debate over its limits led to added protections for liberty"],3,HIST,"Connect the Constitution's stronger framework with the debate described in “The Bill of Rights.”","The founding settlement joined an effective national government with explicit limits and protections added through amendments.")
];
})();
