const APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbw_9bffOl5e_enUY7UoWRsxb0OhJqy-bsN5cfAxwHTkg1Y3rT4MEJJxgGBhXejN9SQXWg/exec";
const ASSIGNMENT_KEY = "AS-B1-CS4-5-INTRO-2026";
const SOURCE_DECLARATION = "https://www.archives.gov/founding-docs/declaration-transcript";
const SOURCE_NW = "https://www.archives.gov/milestone-documents/northwest-ordinance";

const questions = [
q("i01","CS 4","According to the Declaration, why are governments created?",["To secure or protect people's rights","To control all religious beliefs","To give rulers unlimited authority","To prevent citizens from changing government"],0,SOURCE_DECLARATION,"Read the second paragraph beginning “We hold these truths.” Find the words immediately after “That to secure these rights.”","Government exists to secure the people's unalienable rights."),
q("i02","CS 4","Which three rights does the Declaration specifically identify as unalienable?",["Life, liberty, and the pursuit of happiness","Speech, press, and religion","Property, voting, and education","Trial, counsel, and assembly"],0,SOURCE_DECLARATION,"In the second paragraph, find the sentence beginning “We hold these truths.”","The Declaration names life, liberty, and the pursuit of happiness."),
q("i03","CS 4","What does “consent of the governed” mean?",["Government receives legitimate authority from the people","A ruler may govern without elections","Courts must approve every law","Citizens must agree with every decision"],0,SOURCE_DECLARATION,"Read the phrase immediately after “Governments are instituted among Men.”","Consent means legitimate governmental power comes from the people."),
q("i04","CS 4","What responsibility does government have toward individual rights?",["Protect or secure them","Create them whenever convenient","Suspend them permanently during conflict","Give them only to property owners"],0,SOURCE_DECLARATION,"Look for the phrase “to secure these rights.”","The Declaration says government is established to protect or secure rights."),
q("i05","CS 4","According to the Declaration, what may people do when government becomes destructive of their rights?",["Alter or abolish it and establish a new government","Stop all political participation","Transfer power to a foreign king","End all laws permanently"],0,SOURCE_DECLARATION,"Continue reading the second paragraph after “whenever any Form of Government becomes destructive.”","The people may alter or abolish a destructive government and create another."),
q("i06","CS 4","Why does the Declaration say governments should not be changed for “light and transient causes”?",["Stable governments should not be replaced for minor or temporary problems","Kings possess permanent authority","Citizens never have a right to resist","Only Congress may criticize government"],0,SOURCE_DECLARATION,"Read the paragraph beginning “Prudence, indeed.” Focus on the reason for caution.","The Declaration distinguishes serious, repeated abuses from minor or temporary complaints."),
q("i07","CS 4","What evidence does the Declaration present to justify independence?",["A list of repeated injuries and abuses by the king","A proposed Constitution","A list of colonial military victories","A peace treaty with France"],0,SOURCE_DECLARATION,"After the statement of principles, scan the repeated grievances beginning with “He has.”","The grievances serve as evidence that the king repeatedly violated the colonists' rights."),
q("i08","CS 4","Which grievance most directly concerns taxation without representation?",["Imposing taxes without the colonists' consent","Keeping public records far away","Obstructing immigration","Cutting off trade with all parts of the world"],0,SOURCE_DECLARATION,"Scan the grievance list for the sentence that contains both “Taxes” and “Consent.”","The colonists objected to taxes imposed without their consent."),
q("i09","CS 4","Which grievance most directly concerns the right to a jury trial?",["Depriving colonists of trial by jury","Dissolving representative houses","Keeping standing armies","Refusing assent to laws"],0,SOURCE_DECLARATION,"Scan the grievance list for “Trial by Jury.”","The Declaration specifically accuses the king of depriving colonists of jury trials."),
q("i10","CS 4","What political status did the Declaration announce for the colonies?",["Free and independent states","Self-governing British provinces","A temporary military alliance","Territories governed by Parliament"],0,SOURCE_DECLARATION,"Read the final declaration beginning “We, therefore.”","The colonies declared themselves free and independent states."),
q("i11","CS 4","Which power listed near the end demonstrates the new states' independence?",["The power to make war, peace, alliances, and commerce","The power to appoint the British king","The power to dissolve all state governments","The power to control Parliament"],0,SOURCE_DECLARATION,"Read the list of powers following “Free and Independent States.”","Independent states could wage war, make peace, form alliances, and conduct commerce."),
q("i12","CS 4","How did the Declaration change the expected role of government?",["Government was expected to protect rights and depend on the people's consent","Government was expected to grant rights only to nobles","Government became responsible only to military leaders","Government no longer needed laws"],0,SOURCE_DECLARATION,"Connect “secure these rights” with “consent of the governed.”","The Declaration described government as a protector of rights whose legitimate power comes from the people."),
q("i13","CS 4","Which group was most clearly excluded from the Declaration's promise of equality in actual practice in 1776?",["Enslaved people","Royal governors","Members of Parliament","Foreign monarchs"],0,SOURCE_DECLARATION,"Compare “all men are created equal” with who remained enslaved in 1776.","The ideal of equality conflicted sharply with the continued enslavement of African Americans."),
q("i14","CS 4","Why could marginalized groups later use the Declaration's language to demand change?",["Its equality and rights ideals could be applied more broadly than they were in 1776","It prohibited later amendments","It limited rights to the original signers","It rejected the idea of equality"],0,SOURCE_DECLARATION,"Focus on the universal language about equality and unalienable rights.","Later reformers appealed to the Declaration's broad ideals even though those ideals were not equally applied in 1776."),
q("i15","CS 4","Which Enlightenment idea is most visible in the phrase “unalienable Rights”?",["People possess natural rights that government does not create","Monarchs receive absolute power by birth","Government should control religious belief","Citizens surrender every liberty to rulers"],0,SOURCE_DECLARATION,"Look at the rights people are “endowed” with before government is created.","The passage reflects the natural-rights idea that rights exist before government."),
q("i16","CS 4","Which statement best summarizes the Declaration's argument?",["People have rights; government must protect them; persistent abuse can justify political change","Government power comes from military strength alone","Economic complaints are the only reason for independence","All governments should be replaced frequently"],0,SOURCE_DECLARATION,"Follow the sequence in the second paragraph: rights → government → abuse → people's response.","The Declaration builds a logical argument from rights to government's duty and then to justified revolution."),
q("i17","CS 5","Which government adopted the Northwest Ordinance in 1787?",["The Confederation Congress under the Articles of Confederation","The U.S. Congress under the current Constitution","The British Parliament","The Ohio General Assembly"],0,SOURCE_NW,"Read the first explanatory paragraph beneath the document title.","The one-house Confederation Congress adopted the Ordinance while the Articles of Confederation were operating."),
q("i18","CS 5","What was one major purpose of the Northwest Ordinance?",["Create a method for territories to become states","Return western land to Britain","Establish a national monarchy","End settlement west of the Appalachians"],0,SOURCE_NW,"Read the short overview and the numbered list of three principal provisions.","The Ordinance established an orderly process for governing territories and admitting new states."),
q("i19","CS 5","How many states could be formed from the Northwest Territory?",["Not fewer than three and not more than five","Exactly two","As many as Congress wanted without limit","Thirteen"],0,SOURCE_NW,"Look at principal provision number 1.","The territory could be divided into no fewer than three and no more than five states."),
q("i20","CS 5","What happened when a territory reached 5,000 free adult male inhabitants?",["It could elect an assembly and a nonvoting delegate to Congress","It automatically became a state","It could elect the president","Slavery became legal"],0,SOURCE_NW,"Read principal provision number 2 and locate the 5,000-person stage.","At 5,000 free adult male inhabitants, the territory entered the representative stage of government."),
q("i21","CS 5","What population allowed a territory to draft a constitution and request statehood?",["60,000","5,000","10,000","100,000"],0,SOURCE_NW,"Read principal provision number 2 and find the third stage.","A population of 60,000 allowed a territory to draft a constitution and request admission."),
q("i22","CS 5","Why was admission “on an equal footing” important?",["New states would share equal status and participation in the federal Union","New states would remain controlled colonies","Only original states could vote in Congress","New states would have fewer constitutional protections"],0,SOURCE_NW,"In Section 13, find “a share in the federal councils on an equal footing.”","Equal footing meant new states would join the Union as equals rather than remain subordinate territories."),
q("i23","CS 5","Which civil liberty did Article 1 of the Northwest Ordinance protect?",["Religious freedom","The right to bear arms","Freedom from taxation","Universal voting rights"],0,SOURCE_NW,"Go to Article 1 and read the sentence about worship and religious sentiments.","Article 1 protected peaceful religious belief and worship."),
q("i24","CS 5","Which protections appear in Article 2?",["Habeas corpus, trial by jury, moderate fines, and no cruel or unusual punishment","Universal suffrage and free college","Freedom from all taxes","A guaranteed government job"],0,SOURCE_NW,"Go to Article 2 and identify the listed legal protections.","Article 2 included several civil liberties later familiar in American constitutional law."),
q("i25","CS 5","What did the Ordinance say about education?",["Religion, morality, and knowledge supported good government, so schools should be encouraged","Only private tutors could teach","Education was unnecessary for government","Congress would close territorial schools"],0,SOURCE_NW,"Find Article 3 and the sentence beginning “Religion, morality, and knowledge.”","The Ordinance connected education with good government and public happiness."),
q("i26","CS 5","What was the Ordinance's position on slavery and involuntary servitude in the territory?",["It forbade them except as punishment for a crime","It required slavery in every future state","It left the issue entirely to Britain","It ended slavery throughout the entire United States"],0,SOURCE_NW,"Find Article 6 or the overview sentence that says the Ordinance “forbade slavery.”","The Ordinance prohibited slavery and involuntary servitude in the Northwest Territory, except as criminal punishment."),
q("i27","CS 5","How did the Northwest Ordinance help create national unity?",["It provided a common process for territories to join the Union as equal states","It allowed each territory to become a separate country","It prevented western settlement","It gave new states fewer rights than original states"],0,SOURCE_NW,"Combine the three-stage statehood process with the phrase “equal footing.”","A uniform path to equal statehood helped western territories become full parts of the United States."),
q("i28","CS 4–5","What important principle appears in both the Declaration and Northwest Ordinance?",["Government should be connected to rights and the welfare of the people","Government should be controlled by a hereditary monarch","Individual rights should apply only during wartime","Territories should remain permanently unequal"],0,SOURCE_NW,"Compare the Declaration's protection of rights with the Ordinance's territorial bill of rights.","Both documents connected legitimate government with protecting rights and serving the people."),
];

function q(id,cs,prompt,choices,answer,source,where,explanation){return{id,cs,prompt,choices,answer,source,where,explanation,hint:where}}

const state={answers:{},mastered:{},attempts:{},wrongTotal:0,firstStart:new Date().toISOString(),sessions:1,activeSeconds:0,awaySeconds:0,tabLeaves:0,events:[],questionSeconds:{},currentQuestion:null,lastTick:Date.now(),status:"in progress"};
const $=id=>document.getElementById(id); const storageKey=()=>`${ASSIGNMENT_KEY}|${$('email').value.trim().toLowerCase()}`;

function render(){
 $('totalCount').textContent=questions.length;
 $('questions').innerHTML=questions.map((x,n)=>`<article class="question" id="card-${x.id}"><div class="qtop"><span class="qnum">Question ${n+1}</span><span class="cs">${x.cs}</span></div><div class="prompt">${x.prompt}</div><div class="research"><a class="source-link" href="${x.source}" target="_blank" rel="noopener">Open source</a><p class="where"><strong>Where to look:</strong> ${x.where}</p></div><div class="choices">${x.choices.map((c,i)=>`<label class="choice"><input type="radio" name="${x.id}" value="${i}"> <span>${c}</span></label>`).join('')}</div><div class="check-row"><button data-check="${x.id}">Check answer</button></div><div class="feedback" id="fb-${x.id}" role="status"></div></article>`).join('');
 document.querySelectorAll('[data-check]').forEach(b=>b.addEventListener('click',()=>check(b.dataset.check)));
 document.querySelectorAll('.question').forEach(card=>card.addEventListener('focusin',()=>state.currentQuestion=card.id.slice(5)));
 restoreLocal(); update();
}
function check(id){
 const x=questions.find(v=>v.id===id),picked=document.querySelector(`input[name="${id}"]:checked`),fb=$(`fb-${id}`);
 if(!picked){fb.className='feedback hint';fb.textContent='Choose an answer first.';return}
 const value=Number(picked.value); state.answers[id]=value; state.attempts[id]=(state.attempts[id]||0)+1;
 if(value===x.answer){state.mastered[id]=true;fb.className='feedback good';fb.innerHTML=`<strong>Correct.</strong> ${x.explanation}`;$(`card-${id}`).classList.add('mastered');$(`card-${id}`).querySelectorAll('input,button').forEach(el=>el.disabled=true)}
 else{state.wrongTotal++;fb.className='feedback bad';fb.innerHTML=`<strong>Not yet.</strong> Hint: ${x.hint}`}
 saveLocal();update();queueCloudSave();
}
function update(){const m=Object.keys(state.mastered).filter(k=>state.mastered[k]).length,a=Object.values(state.attempts).reduce((s,v)=>s+v,0);$('masteredCount').textContent=m;$('attemptCount').textContent=a;$('barFill').style.width=`${m/questions.length*100}%`;$('submitBtn').disabled=m!==questions.length}
function student(){return{name:$('studentName').value.trim(),period:$('period').value,email:$('email').value.trim().toLowerCase()}}
function payload(){tick();return{assignmentKey:ASSIGNMENT_KEY,student:student(),state:state,answers:state.answers,mastered:state.mastered,score:Object.keys(state.mastered).length,total:questions.length,percent:Math.round(Object.keys(state.mastered).length/questions.length*100),answerCount:Object.keys(state.answers).length,wrongAttempts:state.wrongTotal,updatedAt:new Date().toISOString()}}
function saveLocal(){if(!$('email').value.trim())return;localStorage.setItem(storageKey(),JSON.stringify(payload()))}
function restoreLocal(){const raw=localStorage.getItem(storageKey());if(!raw)return;try{mergeDraft(JSON.parse(raw));$('saveStatus').textContent='Local draft restored.'}catch{}}
function mergeDraft(d){if(!d)return;const s=d.state||d;for(const [k,v] of Object.entries(s.answers||d.answers||{}))if(state.answers[k]===undefined||state.answers[k]==='')state.answers[k]=v;Object.assign(state.mastered,s.mastered||d.mastered||{});for(const[k,v]of Object.entries(s.attempts||{}))state.attempts[k]=Math.max(state.attempts[k]||0,v||0);state.wrongTotal=Math.max(state.wrongTotal||0,s.wrongTotal||d.wrongAttempts||0);state.firstStart=s.firstStart||state.firstStart;applyState()}
function applyState(){for(const x of questions){if(state.answers[x.id]!==undefined){const el=document.querySelector(`input[name="${x.id}"][value="${state.answers[x.id]}"]`);if(el)el.checked=true}if(state.mastered[x.id]){const card=$(`card-${x.id}`),fb=$(`fb-${x.id}`);card.classList.add('mastered');card.querySelectorAll('input,button').forEach(el=>el.disabled=true);fb.className='feedback good';fb.innerHTML=`<strong>Correct.</strong> ${x.explanation}`}}update()}
let saveTimer;function queueCloudSave(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>cloudSave(false),900)}
async function cloudSave(manual){if(!validStudent(false)||APPS_SCRIPT_URL.startsWith('PASTE_')){if(manual)$('saveStatus').textContent=APPS_SCRIPT_URL.startsWith('PASTE_')?'Saved on this device. Add the Apps Script URL for cloud saving.':'Enter name, period, and school email.';return}saveLocal();try{await fetch(APPS_SCRIPT_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({action:'save',payload:JSON.stringify(payload())})});$('saveStatus').textContent='Saved on this device and sent to your teacher draft.'}catch{$('saveStatus').textContent='Saved on this device. Cloud save could not be confirmed.'}}
function loadCloud(){if(!validStudent(true)||APPS_SCRIPT_URL.startsWith('PASTE_'))return;const cb=`load_${Date.now()}`;window[cb]=r=>{try{if(r&&r.found)mergeDraft(r.payload);saveLocal();$('saveStatus').textContent=r&&r.found?'Previous work merged safely.':'No cloud draft was found.'}finally{delete window[cb];script.remove()}};const script=document.createElement('script');script.src=`${APPS_SCRIPT_URL}?action=load&assignmentKey=${encodeURIComponent(ASSIGNMENT_KEY)}&email=${encodeURIComponent(student().email)}&callback=${cb}`;script.onerror=()=>{$('saveStatus').textContent='Could not load the cloud draft.';delete window[cb];script.remove()};document.body.appendChild(script)}
function validStudent(show=true){const s=student(),ok=s.name&&s.period&&/^\S+@\S+\.\S+$/.test(s.email);if(!ok&&show)$('saveStatus').textContent='Enter full name, period, and a valid school email first.';return ok}
function tick(){const now=Date.now(),seconds=Math.max(0,Math.round((now-state.lastTick)/1000));if(document.hidden)state.awaySeconds+=seconds;else state.activeSeconds+=seconds;if(state.currentQuestion)state.questionSeconds[state.currentQuestion]=(state.questionSeconds[state.currentQuestion]||0)+seconds;state.lastTick=now}
setInterval(()=>{tick();saveLocal()},15000);document.addEventListener('visibilitychange',()=>{tick();state.tabLeaves+=document.hidden?1:0;state.events.push({type:document.hidden?'leave':'return',at:new Date().toISOString()})});document.addEventListener('copy',e=>{const card=e.target.closest('.question');state.events.push({type:'copy',question:card?card.id.slice(5):'',at:new Date().toISOString()})});document.addEventListener('paste',e=>{const card=e.target.closest('.question');state.events.push({type:'paste',question:card?card.id.slice(5):'',at:new Date().toISOString()})});
$('studentName').addEventListener('change',restoreLocal);$('email').addEventListener('change',restoreLocal);$('period').addEventListener('change',saveLocal);$('saveBtn').addEventListener('click',()=>cloudSave(true));$('loadBtn').addEventListener('click',loadCloud);$('submitBtn').addEventListener('click',async()=>{if(!validStudent(true))return;state.status='submitted';state.submittedAt=new Date().toISOString();await cloudSave(true);$('submitStatus').textContent='Submitted successfully at 100% mastery.';$('submitBtn').disabled=true});render();

