(function(){
const SP="https://history.state.gov/milestones/1866-1898/spanish-american-war",BIG="https://history.state.gov/milestones/1899-1913/roosevelt-and-monroe-doctrine",WWI="https://history.state.gov/milestones/1914-1920/wwi",PTS="https://www.archives.gov/milestone-documents/president-woodrow-wilsons-14-points",LEAGUE="https://history.state.gov/milestones/1914-1920/league",KELLOGG="https://history.state.gov/milestones/1921-1936/kellogg",MAHAN="https://history.state.gov/milestones/1866-1898/mahan",YELLOW="https://history.state.gov/milestones/1866-1898/yellow-journalism",OPEN="https://history.state.gov/milestones/1899-1913/hay-and-china",CANAL="https://history.state.gov/milestones/1899-1913/panama-canal",PHIL="https://history.state.gov/milestones/1899-1913/war",NAVAL="https://history.state.gov/milestones/1921-1936/naval-conference",PARIS="https://history.state.gov/milestones/1914-1920/paris-peace",DAWES="https://history.state.gov/milestones/1921-1936/dawes";
const q=(id,cs,topic,prompt,choices,answer,source,where,explanation,hint)=>({id,cs,topic,prompt,choices,answer,source,where,explanation,hint});
window.BLOCK_CONFIG={assignmentKey:"AS-B3-CS14-15-VOCAB-2026-v2",title:"Block 3 Vocabulary — World Power and Isolationism",description:"CS 14–15 • Forty essential terms for overseas expansion, World War I, peacemaking, and isolationism.",practice:"Build precise command of the people, policies, events, and foreign-policy concepts needed for lecture and the comprehensive review."};
window.BLOCK_QUESTIONS=[
q("v01","CS 14","Imperialism","What is imperialism?",["A policy of extending control or influence over other territories","A refusal to conduct foreign trade","A system of direct democracy","A peace agreement ending all armies"],0,SP,"Read how the war and overseas possessions expanded U.S. control and influence.","Imperialism extends a nation's political, economic, or military influence over other lands.","Look for expansion of power beyond a nation's borders."),
q("v02","CS 14","Expansionism","What is expansionism?",["Reducing national territory","A policy favoring territorial or international growth","Giving up all naval bases","Avoiding every foreign market"],1,SP,"Identify the actions through which U.S. territory and strategic reach grew.","Expansionism favors extending a nation's territory, markets, or influence.","Which definition involves becoming geographically or internationally larger?"),
q("v03","CS 14","Annexation","What does annexation mean?",["Declaring neutrality","Signing a temporary cease-fire","Formally adding territory to a country","Reducing military spending"],2,SP,"Read how Hawaii became a U.S. territory in 1898.","Annexation is the formal incorporation of territory into a nation.","Think about Hawaii being added to the United States."),
q("v04","CS 14","Yellow Journalism","What was yellow journalism?",["Government censorship of every newspaper","Reporting only official military orders","News printed on yellow paper","Sensationalized reporting designed to attract readers and influence opinion"],3,YELLOW,"Read how sensational newspapers affected public opinion about Cuba.","Yellow journalism emphasized sensational stories, sometimes with exaggeration, to build readership and shape opinion.","The term describes a style of reporting, not a paper color."),
q("v05","CS 14","USS Maine","Why is the USS Maine important?",["Its explosion in Havana intensified calls for war with Spain","It carried Wilson to Versailles","It delivered the Zimmermann Telegram","It founded the League of Nations"],0,SP,"Locate the February 1898 explosion in Havana Harbor.","The unexplained destruction of the Maine fueled public anger and interventionist pressure.","Connect this ship with Havana and the Spanish-American War."),
q("v06","CS 14","Spanish-American War","What was the Spanish-American War?",["A European civil war","An 1898 conflict that expanded U.S. influence in the Caribbean and Pacific","A war caused by the League of Nations","A conflict between the United States and Mexico in 1917"],1,SP,"Read the page title and opening summary.","The 1898 war ended much of Spain's empire and increased U.S. overseas power.","Look for the conflict tied to Cuba, Puerto Rico, Guam, and the Philippines."),
q("v07","CS 14","Treaty of Paris of 1898","What did the Treaty of Paris of 1898 do?",["Created the League of Nations","Ended World War I","Ended the Spanish-American War and transferred overseas territories","Prohibited war as national policy"],2,SP,"Read the paragraphs describing the December 1898 peace settlement.","The treaty ended war with Spain and transferred Puerto Rico, Guam, and the Philippines to U.S. control.","Do not confuse the 1898 Treaty of Paris with the later Versailles settlement."),
q("v08","CS 14","World Power","What is a world power?",["A nation without international interests","A nation controlling every other country","A country that refuses foreign diplomacy","A nation capable of exerting major influence in international affairs"],3,SP,"Read how victory secured U.S. status in the Caribbean and Pacific.","A world power has substantial economic, political, or military influence beyond its region.","Focus on international influence rather than total domination."),
q("v09","CS 14","Big Stick Diplomacy","What was Big Stick diplomacy?",["Negotiation supported by credible military strength","A policy banning naval construction","An agreement to join the League","A plan for secret alliances"],0,BIG,"Read the description of Roosevelt's assertive approach.","Big Stick diplomacy used negotiation backed by the possibility of force.","Recall Roosevelt's phrase about speaking softly."),
q("v10","CS 14","Roosevelt Corollary","What was the Roosevelt Corollary?",["A promise to avoid the Western Hemisphere","An assertion that the United States could intervene in Western Hemisphere disputes","A declaration of war on Germany","A treaty annexing Hawaii"],1,BIG,"Read the paragraph stating when the United States might exercise international police power.","The corollary expanded the Monroe Doctrine into a justification for regional intervention.","Which policy claimed a policing role in nearby nations?"),
q("v11","CS 14","Sphere of Influence","What is a sphere of influence?",["A nation's elected legislature","A neutral ocean zone","An area where a nation exercises special economic or political influence","A military draft district"],2,BIG,"Consider the regional influence claimed by the United States in the Western Hemisphere.","A sphere of influence is a region where one power holds especially strong influence.","The term concerns influence over an area, not formal statehood."),
q("v12","CS 14","Neutrality","What is neutrality?",["Permanent military alliance","Colonial control","Immediate mobilization","A policy of not taking a side in a conflict"],3,WWI,"Read about the United States before its 1917 entry.","Neutrality means remaining outside a conflict rather than supporting one belligerent as a combatant.","Which choice means not choosing either warring side?"),
q("v13","CS 14","Unrestricted Submarine Warfare","What was unrestricted submarine warfare?",["Attacking ships in designated war zones without traditional warning","Using submarines only for rescue","Banning attacks on merchant ships","A U.S. policy of defending Mexico"],0,WWI,"Read Germany's January 1917 decision regarding Allied and neutral shipping.","Germany's policy allowed submarines to attack shipping without the warning expected under older maritime rules.","Look for the policy that endangered passenger, merchant, and neutral ships."),
q("v14","CS 14","Zimmermann Telegram","What was the Zimmermann Telegram?",["Wilson's postwar speech","A German proposal encouraging Mexico to ally against the United States","The Senate's rejection of Versailles","A treaty limiting navies"],1,WWI,"Read the section on the intercepted German message to Mexico.","Germany proposed an alliance and offered to help Mexico recover lost territory.","Which message created a direct security threat near the U.S. border?"),
q("v15","CS 14","Mobilization","What is wartime mobilization?",["Ending military recruitment","Negotiating a peace treaty","Organizing a nation's people, military, and economy for war","Returning all soldiers home"],2,WWI,"Connect U.S. entry with the rapid expansion of military and economic effort.","Mobilization converts national resources and personnel to support a war effort.","The word means preparing and organizing for action."),
q("v16","CS 14","Allies","Who were the Allies in World War I?",["Germany and Austria-Hungary only","Neutral nations only","Countries outside Europe","The coalition including Britain, France, and eventually the United States"],3,WWI,"Read which side received U.S. support and entry.","The United States entered the war alongside the Allied powers.","Identify the coalition opposed to Germany and the Central Powers."),
q("v17","CS 15","Fourteen Points","What were the Fourteen Points?",["Wilson's proposed principles for a just and lasting peace","Fourteen Senate amendments to the Constitution","A list of Spanish colonies","Military orders for invading Germany"],0,PTS,"Read the introductory description of Wilson's January 1918 address.","The Fourteen Points outlined Wilson's peace aims and ideas for preventing future wars.","This was Wilson's blueprint for postwar peace."),
q("v18","CS 15","Self-Determination","What is self-determination?",["A nation conquering its neighbors","The principle that peoples should help decide their own political status","The Senate's power to ratify treaties","A requirement to join military alliances"],1,PTS,"Read the explanation of Wilson's proposals for oppressed nationalities.","Self-determination supports a people's ability to shape its own government and national future.","Focus on who gets to decide a people's political status."),
q("v19","CS 15","Collective Security","What is collective security?",["Each nation refusing all cooperation","One empire controlling world peace","Nations agreeing to respond together against threats to peace","A ban on economic trade"],2,PTS,"Read the description of Wilson's proposed world organization.","Collective security treats aggression against one member as a concern for the broader group.","The word collective means acting together."),
q("v20","CS 15","League of Nations","What was the League of Nations?",["A U.S. military branch","A colonial government in Hawaii","A wartime alliance led by Germany","An international organization created to promote cooperation and peace"],3,PTS,"Read Point XIV and the background explaining the organization it inspired.","The League was designed as an international forum and collective-security organization.","It was Wilson's proposed general association of nations."),
q("v21","CS 15","Treaty of Versailles","What was the Treaty of Versailles?",["The peace treaty with Germany after World War I","The agreement ending the Spanish-American War","The pact annexing Hawaii","The declaration creating the Monroe Doctrine"],0,PARIS,"Read how Allied leaders shaped the peace settlement after World War I.","The Treaty of Versailles set peace terms with Germany and included the League covenant.","Match Versailles with World War I, not 1898."),
q("v22","CS 15","Ratification","What is treaty ratification in the United States?",["A president signing without Congress","Formal Senate approval by the constitutionally required vote","A Supreme Court criminal trial","A public referendum in every state"],1,LEAGUE,"Read about the Senate debate and why the treaty did not take effect for the United States.","Treaties require the Senate's advice and consent before U.S. ratification.","Which chamber has the constitutional treaty role?"),
q("v23","CS 15","Reservationist","Who was a reservationist in the Versailles debate?",["A supporter of unconditional approval","A person rejecting all diplomacy","A senator willing to approve the treaty only with protective conditions","A member of the German delegation"],2,LEAGUE,"Read Lodge’s objections and infer what accepting the treaty with conditions would mean.","Reservationists sought conditions protecting U.S. authority and congressional powers.","The name signals reservations or conditions, not automatic rejection."),
q("v24","CS 15","Irreconcilable","Who was an irreconcilable in the Versailles debate?",["A supporter of Wilson's treaty without changes","A European delegate at Versailles","A voter supporting annexation","A senator fundamentally opposed to the treaty and League membership"],3,LEAGUE,"Read the Senate opposition; infer what fundamental opposition to joining would mean.","Irreconcilables rejected League membership rather than seeking limited amendments.","Which group could not be persuaded by reservations?"),
q("v25","CS 15","Isolationism","What is isolationism?",["A policy limiting political and military entanglements abroad","A ban on all foreign commerce","A plan to annex Europe","A commitment to defend every nation"],0,LEAGUE,"Read how the United States stayed outside the League while participating selectively in diplomacy.","Isolationism seeks to avoid binding foreign political and military commitments.","It is limited involvement—not complete disconnection."),
q("v26","CS 15","Disarmament","What is disarmament?",["Rapidly expanding every army","Reducing weapons or military forces","Creating a secret alliance","Declaring unrestricted submarine warfare"],1,PTS,"Read Point IV concerning national armaments.","Disarmament is the reduction or elimination of weapons and armed forces.","The prefix dis- signals removal or reduction."),
q("v27","CS 15","Kellogg-Briand Pact","What was the Kellogg-Briand Pact?",["A treaty requiring League membership","A plan to divide the Philippines","A multinational agreement renouncing war as national policy","A law banning international trade"],2,KELLOGG,"Read the pact's central promise.","Signatories formally renounced war as a tool of national policy, although enforcement was weak.","Look for the postwar agreement that tried to outlaw war."),
q("v28","CS 15","Foreign Entanglement","What is a foreign entanglement?",["A cultural exchange program","Any overseas purchase","A short diplomatic meeting","A binding commitment that may draw a nation into another country's conflict"],3,LEAGUE,"Read opponents' concerns about League obligations.","Critics used the term for commitments they feared would limit U.S. freedom and create unwanted involvement.","Think about an obligation that could pull the United States into war.")
];
window.BLOCK_QUESTIONS.push(
q("v29","CS 14","Alfred Thayer Mahan","Which idea is most closely associated with Alfred Thayer Mahan?",["Sea power and overseas bases help a nation compete for world markets","Neutrality requires joining every European alliance","The Senate should write peace treaties","Submarines should replace all merchant ships"],0,MAHAN,"Read the discussion of his book and arguments about sea power.","Mahan argued that strong naval forces and bases supported trade and influence.","Find the argument connecting ships, bases, and markets."),
q("v30","CS 14","Naval Base","What is a naval base in the context of overseas expansion?",["A port that supports and supplies military ships","A legislative meeting room","A Spanish peace treaty","A market closed to all foreign merchants"],0,MAHAN,"Find the need for stations that support ships on long routes.","Overseas bases helped vessels refuel, resupply, and operate far from home.","Think about what a ship needs between distant ports."),
q("v31","CS 14","Open Door Policy","What was the Open Door policy in China?",["A proposal for equal commercial opportunity among foreign powers","A ban on American trade with China","A U.S. plan to annex all Chinese territory","An agreement creating the League of Nations"],0,OPEN,"Read Hay’s request about equal commercial access.","The Open Door sought trade access without exclusive control by one power.","Focus on equal access to a market."),
q("v32","CS 14","Philippine-American War","What was the Philippine-American War?",["A conflict after 1898 in which Filipinos resisted U.S. control","A naval battle between Germany and Mexico","A peace conference following World War I","The rebellion that ended Spanish rule in Cuba"],0,PHIL,"Read why Filipino independence leaders opposed U.S. annexation.","Filipino forces fought U.S. rule after Spain ceded the islands.","Identify the group resisting new U.S. control."),
q("v33","CS 14","Panama Canal","Why was the Panama Canal strategically important?",["It shortened travel between the Atlantic and Pacific Oceans","It gave ships a direct route across the Sahara","It ended U.S. trade with Asia","It was the peace settlement with Spain"],0,CANAL,"Read why leaders wanted an isthmian waterway.","The canal shortened shipping and naval travel between oceans.","Think of the long alternative route around South America."),
q("v34","CS 14","Monroe Doctrine","What did the original Monroe Doctrine warn European powers against?",["Further colonization or interference in the Western Hemisphere","Trading with East Asian markets","Negotiating limits on warships","Drafting a peace treaty with Germany"],0,BIG,"Compare the original doctrine with Roosevelt’s later, more active corollary.","The doctrine opposed new European colonial influence in the Americas.","Identify the original warning to Europe."),
q("v35","CS 14","Central Powers","Who were the Central Powers in World War I?",["The coalition led by Germany and Austria-Hungary","Britain, France, and the United States","Only nations that remained neutral","The permanent members of the League"],0,WWI,"Read which side Germany fought for when the United States entered.","Germany and Austria-Hungary were leading Central Powers.","Choose the side opposed by the Allies."),
q("v36","CS 15","Open Diplomacy","What did Wilson mean by open diplomacy?",["Making agreements publicly instead of through secret treaties","Allowing only one nation to trade abroad","Maintaining secret alliances among victors","Permitting unlimited wartime censorship"],0,PTS,"Read Point I of the Fourteen Points.","Wilson proposed openly negotiated agreements to reduce secret commitments.","Look for the opposite of secret treaties."),
q("v37","CS 15","Freedom of the Seas","Which idea matches Wilson's call for freedom of the seas?",["Open navigation outside territorial waters in peace and war, subject to international action","A permanent ban on every merchant ship","Control of all seas by the United States","A requirement that only Allied ships could trade"],0,PTS,"Read Point II and its qualification.","Wilson sought broadly open sea navigation as part of a peaceful order.","Focus on access to navigation."),
q("v38","CS 15","Economic Barriers","What did Wilson want to do with economic barriers among nations?",["Remove barriers and establish more equal trading conditions","Raise tariffs to end all international trade","Give Germany exclusive access to world markets","Replace trade agreements with military alliances"],0,PTS,"Read Point III of the Fourteen Points.","Wilson proposed freer commerce among nations consenting to peace.","Find the proposal concerning trade, not armaments."),
q("v39","CS 15","Reparations","What are war reparations?",["Payments demanded to compensate for wartime losses or damage","A new border around a neutral nation","A promise to reduce every nation's navy","A diplomatic agreement to renounce war"],0,DAWES,"Read why Germany’s payments were disputed after the war.","Reparations are compensation imposed after wartime damage.","Think of a financial obligation after a conflict."),
q("v40","CS 15","Washington Naval Conference","What was the Washington Naval Conference?",["A 1921–22 meeting to limit naval arms and reduce tensions in East Asia","The Senate vote rejecting the Treaty of Paris of 1898","The meeting that created the USS Maine","A German alliance with Mexico"],0,NAVAL,"Read who gathered in Washington and what they discussed.","Major naval powers negotiated limits and addressed Pacific tensions.","Identify the gathering focused on warships after World War I.")
);
// A saved seed keeps choices aligned with saved answer indexes after a reload.
let seed=Number(localStorage.getItem(window.BLOCK_CONFIG.assignmentKey+"|shuffle"));
if(!seed){seed=Math.floor(Math.random()*4294967295)||1;localStorage.setItem(window.BLOCK_CONFIG.assignmentKey+"|shuffle",String(seed))}
function random(){seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;return(seed>>>0)/4294967296}
function shuffle(a){a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
const ordered=shuffle(window.BLOCK_QUESTIONS),positions=shuffle(Array.from({length:ordered.length},(_,i)=>i%4));
window.BLOCK_QUESTIONS=ordered.map((item,n)=>{
 const correct=item.choices[item.answer],wrong=shuffle(item.choices.filter((_,i)=>i!==item.answer));
 const choices=wrong.slice();choices.splice(positions[n],0,correct);
 return{...item,choices,answer:positions[n]};
});
})();
