const APPS_SCRIPT_URL="PASTE_YOUR_APPS_SCRIPT_WEB_APP_URL_HERE",ASSIGNMENT_KEY="AS-B1-CS4-5-REVIEW-2026";
const raw=[
["r01","CS 4","A reform group quotes “all men are created equal” while seeking legal protection for a group excluded in 1776. What use of the Declaration does this demonstrate?",["Applying its ideals more broadly over time","Rejecting natural rights","Defending hereditary rule","Ending consent of the governed"],0,"The Declaration's ideals later became standards reformers used to challenge unequal treatment."],
["r02","CS 4","A government blocks peaceful criticism and refuses citizens any role in choosing leaders. Which two Declaration principles are most directly violated?",["Individual rights and consent of the governed","Federalism and judicial review","Statehood and public education","Commerce and military alliances"],0,"The scenario violates both protected rights and the people's role as the source of legitimate authority."],
["r03","CS 4","Which sequence best represents the Declaration's political argument?",["Natural rights → government protects rights → persistent abuse → people may alter government","Government creates rights → king protects rights → citizens surrender power","War → taxation → monarchy → equality","Statehood → education → trial by jury → independence"],0,"The Declaration moves from rights, to government's purpose, to the consequence of sustained abuse."],
["r04","CS 4","A ruler repeatedly violates rights despite petitions for change. According to the Declaration, what makes resistance justifiable?",["A long pattern of serious abuses","One unpopular temporary policy","A disagreement over a minor issue","The existence of any tax"],0,"The Declaration requires more than a light or temporary complaint; it describes a long train of abuses."],
["r05","CS 4","Which statement correctly distinguishes a natural right from a civil liberty?",["A natural right is inherent; a civil liberty is a legal protection against government interference","Natural rights are created by legislatures; civil liberties exist before government","They are exact synonyms in every historical context","Civil liberties belong only to elected officials"],0,"Natural-right theory treats rights as inherent, while civil liberties are legally protected freedoms."],
["r06","CS 4","Why was listing grievances important to the Declaration's purpose?",["The grievances supplied evidence that Britain had violated the stated principles","They created the first ten amendments","They established the Northwest Territory","They gave Parliament authority over the colonies"],0,"The grievances were the factual support for the colonists' conclusion that separation was justified."],
["r07","CS 4","Which grievance best supports the colonists' claim that representative government had been undermined?",["The king repeatedly dissolved representative houses","The king encouraged colonial elections","Parliament protected jury trials","Britain granted the colonies voting seats in Parliament"],0,"Dissolving representative bodies prevented colonists from governing through their representatives."],
["r08","CS 4","Which grievance later connects most clearly to the Sixth Amendment?",["Depriving colonists of trial by jury","Cutting off trade","Obstructing immigration","Keeping records at distant locations"],0,"The Sixth Amendment protects criminal-trial rights, including trial by an impartial jury."],
["r09","CS 4","Which statement is the best evidence of popular sovereignty in the Declaration?",["Governments derive just powers from the consent of the governed","The colonies may establish commerce","The king employed foreign mercenaries","Governments should not change for minor causes"],0,"Consent of the governed places the source of legitimate governmental authority in the people."],
["r10","CS 4","How did the Declaration redefine the relationship between people and government?",["Government became the people's instrument for protecting rights rather than their unquestioned master","Citizens became subjects with no right to political change","Rights became gifts provided by rulers","Military authority replaced civilian government"],0,"The Declaration made government accountable to the people and to the protection of their rights."],
["r11","CS 4","Why is the Declaration both a historical document and an enduring statement of ideals?",["It announced separation in 1776 and articulated principles later used to evaluate government","It created every modern law","It immediately secured equality for every person","It replaced the Constitution"],0,"The document performed an immediate political act while also stating broader ideals."],
["r12","CS 4","Which conclusion best addresses the contradiction between equality and slavery in 1776?",["The stated ideal was broader than its original application","The Declaration explicitly required slavery","Equality referred only to foreign nations","No colonists recognized the contradiction"],0,"The equality ideal was not applied to enslaved people, even though its language later supported antislavery and civil-rights arguments."],
["r13","CS 4","A student says consent means every citizen must agree with every law. What is the best correction?",["Consent means government receives legitimate authority from the people, not unanimous agreement on every decision","Consent applies only to court decisions","Consent means rulers may ignore elections","Consent prohibits representative government"],0,"Popular consent establishes the source of authority; it does not require unanimous approval of every policy."],
["r14","CS 4","What transformed the colonies' conflict with Britain into a claim for complete political independence?",["The conclusion that repeated abuses made the king unfit to rule a free people","A desire to remain represented in Parliament","A plan to create western territories","A decision to adopt the Constitution"],0,"The Declaration argues that the repeated pattern of tyranny destroyed the legitimacy of British rule."],
["r15","CS 4","Which modern action most clearly reflects the Declaration's principle of consent?",["Citizens choose representatives through elections","A leader inherits office for life","The military cancels an election","Officials govern without legal limits"],0,"Elections are a principal way citizens give or withhold political consent."],
["r16","CS 4","What is the most accurate cause-and-effect relationship?",["Repeated abuses and ignored petitions contributed to the decision to declare independence","Independence caused the earlier grievances","The Northwest Ordinance caused taxation without consent","The Constitution caused the king to dissolve colonial legislatures"],0,"The Declaration presents abuses and failed petitions as causes leading to separation."],
["r17","CS 5","Why is the Northwest Ordinance considered a success of the Articles of Confederation period?",["The Confederation Congress created an effective territorial and statehood policy","It gave Congress an unlimited power to tax","It created the presidency and Supreme Court","It immediately ended slavery nationally"],0,"Despite the Articles' weaknesses, the Confederation Congress established a lasting process for western territories."],
["r18","CS 5","Which sequence correctly describes the Ordinance's territorial process?",["Appointed government → elected assembly and nonvoting delegate → constitution and statehood request","Statehood → appointed governor → return to territorial status","Military rule → independence → British province","Elected president → national court → state legislature"],0,"The Ordinance established three stages leading from territorial administration to possible statehood."],
["r19","CS 5","Why did equal-footing statehood strengthen the Union?",["It promised new states the same standing as the original states","It made western states permanent colonies","It denied new states representation","It required new states to surrender civil liberties"],0,"Equal status encouraged territorial growth to become full participation in the Union."],
["r20","CS 5","A territory has 5,000 free adult male inhabitants. What change did the Ordinance permit?",["An elected assembly and a nonvoting congressional delegate","Immediate statehood","Two voting senators","A separate national government"],0,"Five thousand free adult males triggered the representative stage, not full statehood."],
["r21","CS 5","A territory reaches 60,000 inhabitants. What is the next major step?",["Draft a constitution and request admission as a state","Return to appointed government","Become independent from the United States","Send voting members before becoming a state"],0,"Sixty thousand inhabitants opened the third stage: a constitution and request for statehood."],
["r22","CS 5","Which Northwest Ordinance protection most directly anticipated First Amendment religious liberty?",["People could not be molested for peaceful worship or religious beliefs","All citizens received free land","Congress could tax churches","Only one religion could operate schools"],0,"Article 1 protected religious belief and worship in the territory."],
["r23","CS 5","Which Northwest Ordinance protection most directly anticipated later due-process protections?",["Habeas corpus and judicial proceedings according to common law","The power to form military alliances","The appointment of a territorial governor","The creation of three to five states"],0,"Habeas corpus and lawful judicial procedure protect people from arbitrary government action."],
["r24","CS 5","Why did the Ordinance encourage schools?",["Knowledge and morality were considered necessary for good government and public happiness","Schools would replace elected government","Education would end the statehood process","Congress needed schools to collect tariffs"],0,"The Ordinance explicitly connected education and knowledge with good government."],
["r25","CS 5","Which statement accurately describes the Ordinance's slavery provision?",["It prohibited slavery in the Northwest Territory, with an exception for criminal punishment","It abolished slavery everywhere in the United States","It required every future state to permit slavery","It contained no language about slavery"],0,"Article 6 prohibited slavery and involuntary servitude in the territory except as punishment for crime."],
["r26","CS 5","What limitation should historians remember when evaluating the Ordinance's rights?",["Political participation and many protections were not equally available to everyone","Every adult resident immediately had equal voting rights","The Ordinance eliminated all conflict with American Indians","The document applied equally throughout the existing states"],0,"Its important principles existed alongside exclusions based on race, sex, property, and status."],
["r27","CS 5","Which policy established a precedent for orderly national expansion?",["Admitting territories as equal states after defined stages","Keeping western lands as permanent colonies","Allowing foreign nations to control territories","Preventing residents from forming governments"],0,"The territorial-to-statehood process became a model as the nation expanded."],
["r28","CS 5","Which pair correctly matches a provision with its effect?",["Equal footing — new states entered with equal status","Habeas corpus — governors could imprison without review","Education — schools were discouraged","Article 6 — slavery expanded throughout the territory"],0,"Equal footing made new states constitutional equals of the original states."],
["r29","CS 4–5","What shared theme links the Declaration and the Northwest Ordinance?",["Government should protect rights and operate for the people","Political authority belongs permanently to kings","Rights should disappear during expansion","Western territories should remain unequal"],0,"Both documents connect legitimate government to rights and the public good."],
["r30","CS 4–5","How did the Northwest Ordinance put a Declaration ideal into practice?",["It established protected liberties and representative steps for territorial residents","It restored British rule","It eliminated the right to jury trial","It made new states subordinate to old states"],0,"The Ordinance translated ideals about rights and representative government into territorial policy."],
["r31","CS 4–5","Which comparison is most accurate?",["The Declaration explains why legitimate government must protect rights; the Ordinance lists rights and builds a governing process","Both documents created the presidency","The Declaration organized territories; the Ordinance declared independence","Both documents immediately guaranteed universal equality"],0,"The Declaration states political ideals; the Ordinance applies related principles to governing and admitting territories."],
["r32","CS 4–5","Which claim is best supported by both documents?",["Founding-era Americans increasingly connected government legitimacy with rights, representation, and the people's welfare","Founding-era governments rejected written protections","All Americans enjoyed equal political power by 1787","Territorial growth had no relationship to national unity"],0,"Together the documents show an emerging expectation that government protect rights and represent the people, despite serious exclusions in practice."],
];
const questions=raw.map(x=>({id:x[0],cs:x[1],prompt:x[2],choices:x[3],answer:x[4],explanation:x[5],hint:"Eliminate answers that do not match the document's central principle, then identify the choice that best explains the relationship or effect."}));
questions.sort(()=>Math.random()-.5);
const state={answers:{},mastered:{},attempts:{},wrongTotal:0,firstStart:new Date().toISOString(),sessions:1,activeSeconds:0,awaySeconds:0,tabLeaves:0,events:[],questionSeconds:{},currentQuestion:null,lastTick:Date.now(),status:"in progress"};const $=id=>document.getElementById(id),storageKey=()=>`${ASSIGNMENT_KEY}|${$('email').value.trim().toLowerCase()}`;
function render(){$('totalCount').textContent=questions.length;$('questions').innerHTML=questions.map((x,n)=>`<article class="question" id="card-${x.id}"><div class="qtop"><span class="qnum">Question ${n+1}</span><span class="cs">${x.cs}</span></div><div class="prompt">${x.prompt}</div><div class="choices">${x.choices.map((c,i)=>`<label class="choice"><input type="radio" name="${x.id}" value="${i}"> <span>${c}</span></label>`).join('')}</div><div class="check-row"><button data-check="${x.id}">Check answer</button></div><div class="feedback" id="fb-${x.id}"></div></article>`).join('');document.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>check(b.dataset.check));document.querySelectorAll('.question').forEach(c=>c.onfocusin=()=>state.currentQuestion=c.id.slice(5));restoreLocal();update()}
function check(id){const x=questions.find(v=>v.id===id),p=document.querySelector(`input[name="${id}"]:checked`),f=$(`fb-${id}`);if(!p){f.className='feedback hint';f.textContent='Choose an answer first.';return}const v=+p.value;state.answers[id]=v;state.attempts[id]=(state.attempts[id]||0)+1;if(v===x.answer){state.mastered[id]=true;f.className='feedback good';f.innerHTML=`<strong>Correct.</strong> ${x.explanation}`;const c=$(`card-${id}`);c.classList.add('mastered');c.querySelectorAll('input,button').forEach(e=>e.disabled=true)}else{state.wrongTotal++;f.className='feedback bad';f.innerHTML=`<strong>Not yet.</strong> Hint: ${x.hint}`}saveLocal();update();queueCloudSave()}
function update(){const m=Object.keys(state.mastered).filter(k=>state.mastered[k]).length,a=Object.values(state.attempts).reduce((s,v)=>s+v,0);$('masteredCount').textContent=m;$('attemptCount').textContent=a;$('barFill').style.width=`${m/questions.length*100}%`;$('submitBtn').disabled=m!==questions.length}
function student(){return{name:$('studentName').value.trim(),period:$('period').value,email:$('email').value.trim().toLowerCase()}}function payload(){tick();return{assignmentKey:ASSIGNMENT_KEY,student:student(),state,answers:state.answers,mastered:state.mastered,score:Object.keys(state.mastered).length,total:questions.length,percent:Math.round(Object.keys(state.mastered).length/questions.length*100),answerCount:Object.keys(state.answers).length,wrongAttempts:state.wrongTotal,updatedAt:new Date().toISOString()}}
function saveLocal(){if($('email').value.trim())localStorage.setItem(storageKey(),JSON.stringify(payload()))}function restoreLocal(){const r=localStorage.getItem(storageKey());if(r)try{mergeDraft(JSON.parse(r));$('saveStatus').textContent='Local draft restored.'}catch{}}
function mergeDraft(d){const s=d.state||d;if(!d)return;for(const[k,v]of Object.entries(s.answers||d.answers||{}))if(state.answers[k]===undefined||state.answers[k]==='')state.answers[k]=v;Object.assign(state.mastered,s.mastered||d.mastered||{});for(const[k,v]of Object.entries(s.attempts||{}))state.attempts[k]=Math.max(state.attempts[k]||0,v||0);state.wrongTotal=Math.max(state.wrongTotal,s.wrongTotal||d.wrongAttempts||0);state.firstStart=s.firstStart||state.firstStart;applyState()}
function applyState(){questions.forEach(x=>{if(state.answers[x.id]!==undefined){const e=document.querySelector(`input[name="${x.id}"][value="${state.answers[x.id]}"]`);if(e)e.checked=true}if(state.mastered[x.id]){const c=$(`card-${x.id}`),f=$(`fb-${x.id}`);c.classList.add('mastered');c.querySelectorAll('input,button').forEach(e=>e.disabled=true);f.className='feedback good';f.innerHTML=`<strong>Correct.</strong> ${x.explanation}`}});update()}
let saveTimer;function queueCloudSave(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>cloudSave(false),900)}async function cloudSave(manual){if(!valid(false)||APPS_SCRIPT_URL.startsWith('PASTE_')){if(manual)$('saveStatus').textContent=APPS_SCRIPT_URL.startsWith('PASTE_')?'Saved on this device. Add the Apps Script URL for cloud saving.':'Enter name, period, and school email.';return}saveLocal();try{await fetch(APPS_SCRIPT_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({action:'save',payload:JSON.stringify(payload())})});$('saveStatus').textContent='Saved on this device and sent to your teacher draft.'}catch{$('saveStatus').textContent='Saved on this device. Cloud save could not be confirmed.'}}
function loadCloud(){if(!valid(true)||APPS_SCRIPT_URL.startsWith('PASTE_'))return;const cb=`load_${Date.now()}`,s=document.createElement('script');window[cb]=r=>{try{if(r&&r.found)mergeDraft(r.payload);saveLocal();$('saveStatus').textContent=r&&r.found?'Previous work merged safely.':'No cloud draft was found.'}finally{delete window[cb];s.remove()}};s.src=`${APPS_SCRIPT_URL}?action=load&assignmentKey=${encodeURIComponent(ASSIGNMENT_KEY)}&email=${encodeURIComponent(student().email)}&callback=${cb}`;s.onerror=()=>{$('saveStatus').textContent='Could not load the cloud draft.';delete window[cb];s.remove()};document.body.appendChild(s)}function valid(show=true){const x=student(),ok=x.name&&x.period&&/^\S+@\S+\.\S+$/.test(x.email);if(!ok&&show)$('saveStatus').textContent='Enter full name, period, and a valid school email first.';return ok}
function tick(){const n=Date.now(),sec=Math.max(0,Math.round((n-state.lastTick)/1000));if(document.hidden)state.awaySeconds+=sec;else state.activeSeconds+=sec;if(state.currentQuestion)state.questionSeconds[state.currentQuestion]=(state.questionSeconds[state.currentQuestion]||0)+sec;state.lastTick=n}setInterval(()=>{tick();saveLocal()},15000);document.addEventListener('visibilitychange',()=>{tick();if(document.hidden)state.tabLeaves++;state.events.push({type:document.hidden?'leave':'return',at:new Date().toISOString()})});document.addEventListener('copy',e=>state.events.push({type:'copy',question:e.target.closest('.question')?.id.slice(5)||'',at:new Date().toISOString()}));document.addEventListener('paste',e=>state.events.push({type:'paste',question:e.target.closest('.question')?.id.slice(5)||'',at:new Date().toISOString()}));$('studentName').onchange=restoreLocal;$('email').onchange=restoreLocal;$('period').onchange=saveLocal;$('saveBtn').onclick=()=>cloudSave(true);$('loadBtn').onclick=loadCloud;$('submitBtn').onclick=async()=>{if(!valid(true))return;state.status='submitted';state.submittedAt=new Date().toISOString();await cloudSave(true);$('submitStatus').textContent='Submitted successfully at 100% mastery.';$('submitBtn').disabled=true};render();
